package com.company.platform.scheduler;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/** Converts the platform workflow snapshot into DolphinScheduler 3.1.x API payloads. */
public final class DolphinSchedulerProcessConverter {
    private final ObjectMapper mapper;
    private final int defaultFailRetryTimes;
    private final int defaultFailRetryInterval;
    private final String defaultWorkerGroup;

    public DolphinSchedulerProcessConverter(ObjectMapper mapper) {
        this(mapper, 3, 1, "default");
    }

    public DolphinSchedulerProcessConverter(ObjectMapper mapper, int defaultFailRetryTimes,
                                             int defaultFailRetryInterval, String defaultWorkerGroup) {
        this.mapper = mapper;
        this.defaultFailRetryTimes = clamp(defaultFailRetryTimes, 0, 10);
        this.defaultFailRetryInterval = clamp(defaultFailRetryInterval, 1, 60);
        this.defaultWorkerGroup = defaultWorkerGroup == null || defaultWorkerGroup.isBlank()
                ? "default" : defaultWorkerGroup.trim();
    }

    public ProcessPayload convert(String definitionJson, long projectCode, String tenantCode, String userName) {
        try {
            JsonNode root = mapper.readTree(definitionJson);
            ArrayNode platformNodes = asArray(root, "nodes");
            if (platformNodes.isEmpty()) throw new IllegalArgumentException("工作流至少需要一个 DolphinScheduler 节点");

            Map<Long, Long> taskCodes = new HashMap<>();
            ArrayNode taskDefinitions = mapper.createArrayNode();
            ArrayNode locations = mapper.createArrayNode();
            long sequence = 1;
            for (JsonNode node : platformNodes) {
                long nodeId = node.path("id").asLong(sequence);
                long taskCode = taskCode(projectCode, nodeId, sequence++);
                taskCodes.put(nodeId, taskCode);
                taskDefinitions.add(taskDefinition(node, taskCode, projectCode, userName));

                ObjectNode location = mapper.createObjectNode();
                location.put("taskCode", taskCode);
                location.put("x", node.path("x").asInt(0));
                location.put("y", node.path("y").asInt(0));
                locations.add(location);
            }

            ArrayNode relations = mapper.createArrayNode();
            Set<Long> targets = new HashSet<>();
            for (JsonNode edge : asArray(root, "edges")) {
                long source = taskCodes.getOrDefault(edge.path("sourceNodeId").asLong(), 0L);
                long target = taskCodes.getOrDefault(edge.path("targetNodeId").asLong(), 0L);
                if (source == 0 || target == 0) {
                    throw new IllegalArgumentException("工作流连线引用了不存在的节点");
                }
                relations.add(relation(projectCode, source, target));
                targets.add(target);
            }
            // DolphinScheduler requires a relation entry for every root task. A zero pre-task
            // code represents a workflow root and is how the official UI persists such nodes.
            for (long taskCode : taskCodes.values()) {
                if (!targets.contains(taskCode)) relations.add(relation(projectCode, 0, taskCode));
            }

            String taskDefinitionsJson = mapper.writeValueAsString(taskDefinitions);
            String relationsJson = mapper.writeValueAsString(relations);
            String locationsJson = mapper.writeValueAsString(locations);
            return new ProcessPayload(root.path("workflowCode").asText(), root.path("name").asText(),
                    root.path("description").asText(""), locationsJson, taskDefinitionsJson, relationsJson,
                    root.path("version").asInt(1), tenantCode);
        } catch (IllegalArgumentException ex) {
            throw ex;
        } catch (Exception ex) {
            throw new IllegalArgumentException("工作流快照转换失败：" + ex.getMessage(), ex);
        }
    }

    private ObjectNode taskDefinition(JsonNode node, long taskCode, long projectCode, String userName) {
        String type = node.path("type").asText("SHELL").toUpperCase();
        ObjectNode config = nodeConfig(node);
        ObjectNode task = mapper.createObjectNode();
        task.put("code", taskCode);
        task.put("name", node.path("name").asText("platform-task"));
        task.put("version", 1);
        task.put("description", "Generated by BigData Platform");
        task.put("projectCode", projectCode);
        task.put("userName", userName);
        task.put("taskType", type);
        task.set("taskParams", taskParams(node, type, config));
        task.put("flag", "YES");
        task.put("taskPriority", config.path("taskPriority").asText("MEDIUM"));
        task.put("workerGroup", text(config, "workerGroup", defaultWorkerGroup));
        task.put("environmentCode", config.path("environmentCode").asLong(-1));
        task.put("failRetryTimes", clamp(integer(config, "failRetryTimes", "retryTimes", defaultFailRetryTimes), 0, 10));
        task.put("failRetryInterval", clamp(integer(config, "failRetryInterval", "retryIntervalMinutes", defaultFailRetryInterval), 1, 60));
        task.put("timeoutFlag", "CLOSE");
        task.put("timeout", 0);
        task.put("delayTime", 0);
        task.put("resourceIds", "");
        task.put("taskGroupId", 0);
        task.put("taskGroupPriority", 0);
        task.put("cpuQuota", -1);
        task.put("memoryMax", -1);
        return task;
    }

    private ObjectNode taskParams(JsonNode node, String type, ObjectNode config) {
        String content = decodeContent(node);

        if ("SEATUNNEL".equals(type)) {
            ObjectNode params = mapper.createObjectNode();
            params.put("startupScript", config.path("startupScript").asText("seatunnel.sh"));
            params.put("useCustom", true);
            params.put("rawScript", config.path("rawScript").asText(content));
            params.set("resourceList", mapper.createArrayNode());
            return params;
        }
        if ("SQL".equals(type)) {
            int datasourceId = config.path("datasourceId").asInt(0);
            if (datasourceId <= 0) {
                throw new IllegalArgumentException("SQL 节点“" + node.path("name").asText("platform-task")
                        + "”必须在 configJson 中配置有效的 DolphinScheduler datasourceId");
            }
            ObjectNode params = mapper.createObjectNode();
            params.put("type", config.path("type").asText("MYSQL"));
            params.put("datasource", datasourceId);
            params.put("sql", config.path("sql").asText(content));
            params.put("sqlType", config.path("sqlType").asInt(0));
            params.put("displayRows", config.path("displayRows").asInt(10));
            params.put("limit", config.path("limit").asInt(0));
            params.set("preStatements", mapper.createArrayNode());
            params.set("postStatements", mapper.createArrayNode());
            params.set("localParams", mapper.createArrayNode());
            params.set("udfs", mapper.createArrayNode());
            return params;
        }
        ObjectNode params = mapper.createObjectNode();
        params.put("rawScript", content);
        params.set("resourceList", mapper.createArrayNode());
        return params;
    }

    private ObjectNode nodeConfig(JsonNode node) {
        JsonNode rawConfig = node.get("configJson");
        if (rawConfig != null && rawConfig.isTextual()) return readObject(rawConfig.asText());
        if (rawConfig != null && rawConfig.isObject()) return (ObjectNode) rawConfig.deepCopy();
        return mapper.createObjectNode();
    }

    private int integer(ObjectNode config, String primary, String alias, int defaultValue) {
        JsonNode primaryNode = config.get(primary);
        if (primaryNode != null && !primaryNode.isNull()) return primaryNode.asInt(defaultValue);
        JsonNode aliasNode = config.get(alias);
        return aliasNode == null || aliasNode.isNull() ? defaultValue : aliasNode.asInt(defaultValue);
    }

    private String text(ObjectNode config, String field, String defaultValue) {
        String value = config.path(field).asText(defaultValue);
        return value == null || value.isBlank() ? defaultValue : value.trim();
    }

    private static int clamp(int value, int min, int max) {
        return Math.max(min, Math.min(max, value));
    }

    private ObjectNode relation(long projectCode, long preTaskCode, long postTaskCode) {
        ObjectNode relation = mapper.createObjectNode();
        relation.put("name", "");
        relation.put("projectCode", projectCode);
        relation.put("preTaskCode", preTaskCode);
        relation.put("preTaskVersion", 1);
        relation.put("postTaskCode", postTaskCode);
        relation.put("postTaskVersion", 1);
        relation.put("conditionType", "NONE");
        relation.put("conditionParams", "{}");
        return relation;
    }

    private String decodeContent(JsonNode node) {
        String encoded = node.path("contentBase64").asText("");
        if (encoded.isBlank()) return "";
        return new String(Base64.getDecoder().decode(encoded), StandardCharsets.UTF_8);
    }

    private ObjectNode readObject(String json) {
        try {
            JsonNode node = mapper.readTree(json == null || json.isBlank() ? "{}" : json);
            return node != null && node.isObject() ? (ObjectNode) node : mapper.createObjectNode();
        } catch (Exception ex) {
            throw new IllegalArgumentException("节点配置不是合法 JSON：" + ex.getMessage(), ex);
        }
    }

    private ArrayNode asArray(JsonNode root, String field) {
        JsonNode node = root.path(field);
        return node.isArray() ? (ArrayNode) node : mapper.createArrayNode();
    }

    private long taskCode(long projectCode, long nodeId, long sequence) {
        long value = Math.abs(projectCode % 1_000_000_000_000L) * 100_000L
                + Math.abs(nodeId % 10_000L) * 10L + (sequence % 10L);
        return value == 0 ? sequence : value;
    }

    public record ProcessPayload(String workflowCode, String name, String description, String locations,
                                 String taskDefinitions, String relations, int version, String tenantCode) {
    }
}
