<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { formatDateTime, statusLabel as commonStatusLabel } from '../../utils/display'
import { operationsApi, type AlertItem, type FailureItem, type OperationInstance, type OperationSummary } from '../../api/domain'
const route=useRoute();const loading=ref(true);const summary=ref<OperationSummary|null>(null),instances=ref<OperationInstance[]>([]),failures=ref<FailureItem[]>([]),alerts=ref<AlertItem[]>([])
const mode=computed(()=>route.path.split('/').pop()||'overview')
const title=computed(()=>({overview:'运维总览',instances:'运行实例',failures:'失败任务',alerts:'告警中心'} as any)[mode.value]||'运维中心')
const subtitle=computed(()=>mode.value==='overview'?'统一查看工作流、SeaTunnel 与 Flink CDC 的运行状态。':mode.value==='instances'?'查看平台统一运行实例。':mode.value==='failures'?'集中处理需要人工介入的失败任务。':'查看由真实运行失败聚合出的告警。')
async function load(){loading.value=true;try{if(mode.value==='overview')summary.value=await operationsApi.summary();if(mode.value==='instances')instances.value=await operationsApi.instances();if(mode.value==='failures')failures.value=await operationsApi.failures();if(mode.value==='alerts')alerts.value=await operationsApi.alerts()}catch(e){ElMessage.error(e instanceof Error?e.message:'运维数据加载失败')}finally{loading.value=false}}
async function stop(r:OperationInstance){try{await ElMessageBox.confirm(`停止“${r.name}”？`,'停止实例',{type:'warning'});await operationsApi.stop(r.type,r.id);ElMessage.success('停止请求已提交');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'停止失败')}}
async function rerun(r:OperationInstance){try{await operationsApi.rerun(r.id);ElMessage.success('重跑实例已提交');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'重跑失败')}}
function fmt(v?:string){return formatDateTime(v)}
function statusLabel(status?:string){return commonStatusLabel(status)}
watch(()=>route.path,load);onMounted(load)
</script>
<template><div class="ds-page"><PageHeader :title="title" :subtitle="subtitle"/>
<el-skeleton v-if="loading" :rows="7" animated/>
<template v-else-if="mode==='overview'&&summary"><div class="ds-grid-4"><div class="ds-card ds-metric"><div class="ds-metric__label">运行实例</div><div class="ds-metric__value">{{summary.total}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">运行中</div><div class="ds-metric__value">{{summary.running}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">成功</div><div class="ds-metric__value">{{summary.success}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">失败</div><div class="ds-metric__value danger-value">{{summary.failed}}</div></div></div><div class="ds-card ds-section-gap"><div class="ds-card__head"><div><div class="ds-card__title">运维边界</div><div class="ds-card__sub">实例状态来自 Local Scheduler、SeaTunnel 和 Flink CDC，不展示虚拟平台健康数据。</div></div></div><div class="overview-note"><div><strong>Local Scheduler</strong><span>工作流实例 / 任务实例 / 重跑 / 停止</span></div><div><strong>SeaTunnel</strong><span>离线同步执行实例</span></div><div><strong>Flink CDC</strong><span>实时作业运行与失败状态</span></div></div></div></template>
<div v-else-if="mode==='instances'" class="ds-card"><div v-if="!instances.length" class="ds-empty"><div><div class="ds-empty__title">暂无运行实例</div></div></div><table v-else class="ds-table"><thead><tr><th>名称</th><th>状态</th><th>开始时间</th><th>结束时间</th><th>操作</th></tr></thead><tbody><tr v-for="r in instances" :key="`${r.type}-${r.id}`"><td class="ds-resource">{{r.name}}</td><td><StatusBadge :status="r.status" :label="statusLabel(r.status)"/></td><td>{{fmt(r.startedAt||r.createdAt)}}</td><td>{{fmt(r.finishedAt)}}</td><td><span v-if="/RUNNING|START/i.test(r.status)" class="danger" @click="stop(r)">停止</span><span v-if="r.type==='WORKFLOW'&&/FAIL|STOP|SUCCESS/i.test(r.status)" class="ds-link" @click="rerun(r)">重跑</span></td></tr></tbody></table></div>
<div v-else-if="mode==='failures'" class="ds-card"><div v-if="!failures.length" class="ds-empty"><div><div class="ds-empty__title">当前无失败任务</div></div></div><table v-else class="ds-table"><thead><tr><th>任务</th><th>类型</th><th>引擎</th><th>状态</th><th>尝试次数</th><th>错误</th><th>开始时间</th></tr></thead><tbody><tr v-for="r in failures" :key="`${r.type}-${r.id}`"><td class="ds-resource">{{r.name}}</td><td>{{r.type}}</td><td>{{r.engine}}</td><td><StatusBadge :status="r.status"/></td><td>{{r.attemptNo}}</td><td :title="r.errorMessage">{{r.errorMessage||'—'}}</td><td>{{fmt(r.startedAt)}}</td></tr></tbody></table></div>
<div v-else class="ds-card"><div v-if="!alerts.length" class="ds-empty"><div><div class="ds-empty__title">当前无告警</div><div>失败实例会自动聚合到这里。</div></div></div><table v-else class="ds-table"><thead><tr><th>告警</th><th>资源</th><th>状态</th><th>信息</th><th>发生时间</th><th>处理状态</th></tr></thead><tbody><tr v-for="r in alerts" :key="`${r.resourceType}-${r.resourceId}`"><td>{{r.alertType}}</td><td class="ds-resource">{{r.name}}</td><td><StatusBadge :status="r.status"/></td><td>{{r.message||'—'}}</td><td>{{fmt(r.occurredAt)}}</td><td>{{commonStatusLabel(r.handlingState)}}</td></tr></tbody></table></div>
</div></template><style scoped>.danger-value{color:#b42318}.danger{color:#d92d20;cursor:pointer}.overview-note{display:grid;grid-template-columns:repeat(3,1fr);gap:0;padding:18px}.overview-note>div{padding:12px 18px;border-right:1px solid var(--ds-border-soft)}.overview-note>div:last-child{border-right:0}.overview-note strong,.overview-note span{display:block}.overview-note span{margin-top:6px;color:#98a2b3;font-size:11px}</style>