<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { formatDateTime, statusLabel as commonStatusLabel } from '../../utils/display'
import { operationsApi, type AlertItem, type FailureItem, type OperationInstance, type OperationSummary, type OperationTask } from '../../api/domain'

const route=useRoute()
const loading=ref(true),summary=ref<OperationSummary|null>(null),tasks=ref<OperationTask[]>([]),instances=ref<OperationInstance[]>([]),failures=ref<FailureItem[]>([]),alerts=ref<AlertItem[]>([])
const taskType=ref('ALL'),keyword=ref(''),busy=ref(new Set<string>()),detailOpen=ref(false),detail=ref<OperationTask>(),logOpen=ref(false),logTitle=ref('运行日志'),logText=ref('')
const mode=computed(()=>route.path.split('/').pop()||'overview')
const title=computed(()=>({overview:'运维总览',tasks:'任务运维',instances:'运行实例',failures:'失败任务',alerts:'告警中心'} as Record<string,string>)[mode.value]||'运维中心')
const subtitle=computed(()=>({overview:'统一监控离线集成、实时集成和数据开发任务。',tasks:'只提供生产运维操作，不允许在运维中心修改任务配置。',instances:'查看三类任务的实际运行实例。',failures:'集中查看需要人工处理的失败任务。',alerts:'展示已经真实推送到告警渠道的历史记录。'} as Record<string,string>)[mode.value]||'')
const filteredTasks=computed(()=>tasks.value.filter(x=>(taskType.value==='ALL'||x.type===taskType.value)&&(!keyword.value.trim()||x.name.toLowerCase().includes(keyword.value.trim().toLowerCase()))))
const typeLabel=(v:string)=>({OFFLINE:'离线集成',REALTIME:'实时集成',DEVELOPMENT:'数据开发'} as Record<string,string>)[v]||v
const lifecycleLabel=(v?:string)=>({ONLINE:'已上线',OFFLINE:'已下线',PUBLISHED:'已发布',DRAFT:'草稿'} as Record<string,string>)[String(v||'').toUpperCase()]||v||'—'
const key=(action:string,row:OperationTask)=>`${action}-${row.type}-${row.id}`
const isBusy=(action:string,row:OperationTask)=>busy.value.has(key(action,row))
function setBusy(action:string,row:OperationTask,value:boolean){const n=new Set(busy.value);value?n.add(key(action,row)):n.delete(key(action,row));busy.value=n}
function fmt(v?:string){return formatDateTime(v)}
function statusLabel(v?:string){return commonStatusLabel(v)}

async function load(){loading.value=true;try{if(mode.value==='overview')summary.value=await operationsApi.summary();if(mode.value==='tasks')tasks.value=await operationsApi.tasks();if(mode.value==='instances')instances.value=await operationsApi.instances();if(mode.value==='failures')failures.value=await operationsApi.failures();if(mode.value==='alerts')alerts.value=await operationsApi.alerts()}catch(e){ElMessage.error(e instanceof Error?e.message:'运维数据加载失败')}finally{loading.value=false}}
async function taskAction(action:'start'|'rerun'|'kill',row:OperationTask){const names={start:'启动',rerun:'重跑',kill:'杀死'};const name=names[action];try{await ElMessageBox.confirm(`确认${name}任务“${row.name}”？${action==='kill'?'运行中的实例将被终止。':''}`,`${name}确认`,{type:action==='kill'?'error':'warning',confirmButtonText:`确认${name}`,cancelButtonText:'取消'});setBusy(action,row,true);if(action==='start')await operationsApi.startTask(row.type,row.id);else if(action==='rerun')await operationsApi.rerunTask(row.type,row.id);else await operationsApi.killTask(row.type,row.id);ElMessage.success(action==='kill'?'杀死操作已执行':`${name}请求已成功提交`);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:`${name}失败`)}finally{setBusy(action,row,false)}}
async function showLog(row:OperationTask){try{logTitle.value=`${row.name} · 运行日志`;logText.value='正在加载日志...';logOpen.value=true;logText.value=await operationsApi.taskLog(row.type,row.id)}catch(e){logText.value=e instanceof Error?e.message:'日志加载失败'}}
function showDetail(row:OperationTask){detail.value=row;detailOpen.value=true}
async function stopInstance(r:OperationInstance){try{await ElMessageBox.confirm(`确认杀死“${r.name}”当前实例？`,'杀死确认',{type:'error',confirmButtonText:'确认杀死',cancelButtonText:'取消'});await operationsApi.stop(r.type,r.id);ElMessage.success('杀死请求已执行');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'杀死失败')}}
async function instanceLog(r:OperationInstance){try{logTitle.value=`${r.name} · 实例日志`;logText.value='正在加载日志...';logOpen.value=true;logText.value=await operationsApi.log(r.type,r.id)}catch(e){logText.value=e instanceof Error?e.message:'日志加载失败'}}
watch(()=>route.path,load);onMounted(load)
</script>

<template><div class="ds-page"><PageHeader :title="title" :subtitle="subtitle"/>
<el-skeleton v-if="loading" :rows="7" animated/>
<template v-else-if="mode==='overview'&&summary"><div class="ds-grid-4"><div class="ds-card ds-metric"><div class="ds-metric__label">生产任务</div><div class="ds-metric__value">{{summary.total}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">运行中</div><div class="ds-metric__value">{{summary.running}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">最近成功</div><div class="ds-metric__value">{{summary.success}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">最近失败</div><div class="ds-metric__value danger-value">{{summary.failed}}</div></div></div><div class="ds-card ds-section-gap"><div class="overview-note"><div><strong>离线集成</strong><span>SeaTunnel · 启动 / 重跑 / 杀死 / 日志</span></div><div><strong>实时集成</strong><span>Flink CDC · 启动 / 重跑 / 杀死 / 日志</span></div><div><strong>数据开发</strong><span>StarRocks · 生产版本运行 / 重跑 / 杀死 / 日志</span></div></div></div></template>

<div v-else-if="mode==='tasks'" class="ds-card task-card"><div class="task-toolbar"><div class="task-types"><button v-for="x in [{k:'ALL',n:'全部任务'},{k:'OFFLINE',n:'离线集成'},{k:'REALTIME',n:'实时集成'},{k:'DEVELOPMENT',n:'数据开发'}]" :key="x.k" :class="{active:taskType===x.k}" @click="taskType=x.k">{{x.n}}</button></div><el-input v-model="keyword" clearable placeholder="搜索任务名称" style="width:240px"/></div><div v-if="!filteredTasks.length" class="ds-empty"><div><div class="ds-empty__title">暂无任务</div></div></div><table v-else class="ds-table task-table"><thead><tr><th>任务名称</th><th>任务类型</th><th>执行引擎</th><th>生产状态</th><th>运行状态</th><th>最近开始</th><th>最近结束</th><th class="op-col">操作</th></tr></thead><tbody><tr v-for="r in filteredTasks" :key="`${r.type}-${r.id}`"><td><div class="task-name">{{r.name}}</div><small>{{r.owner||'platform'}}</small></td><td>{{typeLabel(r.type)}}</td><td>{{r.engine}}</td><td><span class="lifecycle" :class="String(r.lifecycleStatus).toLowerCase()">{{lifecycleLabel(r.lifecycleStatus)}}</span></td><td><StatusBadge :status="r.runtimeStatus" :label="statusLabel(r.runtimeStatus)"/></td><td>{{fmt(r.lastStartedAt)}}</td><td>{{fmt(r.lastFinishedAt)}}</td><td class="task-actions"><el-button link type="primary" @click="showDetail(r)">详情</el-button><el-button link type="primary" :loading="isBusy('start',r)" :disabled="!r.canStart" @click="taskAction('start',r)">启动</el-button><el-button link type="primary" :loading="isBusy('rerun',r)" :disabled="!r.canRerun" @click="taskAction('rerun',r)">重跑</el-button><el-button link type="danger" :loading="isBusy('kill',r)" :disabled="!r.canKill" @click="taskAction('kill',r)">杀死</el-button><el-button link type="primary" :disabled="!r.lastExecutionId" @click="showLog(r)">日志</el-button></td></tr></tbody></table></div>

<div v-else-if="mode==='instances'" class="ds-card"><div v-if="!instances.length" class="ds-empty"><div><div class="ds-empty__title">暂无运行实例</div></div></div><table v-else class="ds-table"><thead><tr><th>名称</th><th>类型</th><th>状态</th><th>开始时间</th><th>结束时间</th><th>操作</th></tr></thead><tbody><tr v-for="r in instances" :key="`${r.type}-${r.id}`"><td class="ds-resource">{{r.name}}</td><td>{{typeLabel(r.type)}}</td><td><StatusBadge :status="r.status" :label="statusLabel(r.status)"/></td><td>{{fmt(r.startedAt||r.createdAt)}}</td><td>{{fmt(r.finishedAt)}}</td><td><el-button link type="primary" @click="instanceLog(r)">日志</el-button><el-button v-if="/RUNNING|START/i.test(r.status)" link type="danger" @click="stopInstance(r)">杀死</el-button></td></tr></tbody></table></div>
<div v-else-if="mode==='failures'" class="ds-card"><div v-if="!failures.length" class="ds-empty"><div><div class="ds-empty__title">当前无失败任务</div></div></div><table v-else class="ds-table"><thead><tr><th>任务</th><th>类型</th><th>引擎</th><th>状态</th><th>错误</th><th>开始时间</th></tr></thead><tbody><tr v-for="r in failures" :key="`${r.type}-${r.id}`"><td class="ds-resource">{{r.name}}</td><td>{{typeLabel(r.type)}}</td><td>{{r.engine}}</td><td><StatusBadge :status="r.status" :label="statusLabel(r.status)"/></td><td class="error-cell" :title="r.errorMessage">{{r.errorMessage||'—'}}</td><td>{{fmt(r.startedAt)}}</td></tr></tbody></table></div>
<div v-else class="ds-card"><div v-if="!alerts.length" class="ds-empty"><div><div class="ds-empty__title">暂无推送历史</div><div>只有真正执行过告警推送的记录才会显示在这里。</div></div></div><table v-else class="ds-table"><thead><tr><th>推送渠道</th><th>任务</th><th>任务状态</th><th>告警内容</th><th>推送时间</th><th>推送结果</th></tr></thead><tbody><tr v-for="r in alerts" :key="`${r.resourceId}-${r.occurredAt}`"><td>{{r.alertType}} · {{r.resourceType}}</td><td class="ds-resource">{{r.name}}</td><td><StatusBadge :status="r.status" :label="statusLabel(r.status)"/></td><td>{{r.message||'—'}}</td><td>{{fmt(r.occurredAt)}}</td><td><StatusBadge :status="r.handlingState" :label="r.handlingState==='SUCCESS'?'成功':'失败'"/></td></tr></tbody></table></div>

<el-drawer v-model="detailOpen" title="任务详情" size="520px"><template v-if="detail"><div class="detail-grid"><div><span>任务名称</span><strong>{{detail.name}}</strong></div><div><span>任务类型</span><strong>{{typeLabel(detail.type)}}</strong></div><div><span>执行引擎</span><strong>{{detail.engine}}</strong></div><div><span>负责人</span><strong>{{detail.owner}}</strong></div><div><span>生产状态</span><strong>{{lifecycleLabel(detail.lifecycleStatus)}}</strong></div><div><span>运行状态</span><strong>{{statusLabel(detail.runtimeStatus)}}</strong></div><div><span>最近执行 ID</span><strong>{{detail.lastExecutionId||'—'}}</strong></div><div><span>最近开始</span><strong>{{fmt(detail.lastStartedAt)}}</strong></div><div><span>最近结束</span><strong>{{fmt(detail.lastFinishedAt)}}</strong></div></div><div v-if="detail.errorMessage" class="detail-error">{{detail.errorMessage}}</div><div class="readonly-tip">运维中心只允许查看和运行控制，不提供任务配置修改入口。</div></template></el-drawer>
<el-dialog v-model="logOpen" :title="logTitle" width="860px" top="8vh"><pre class="log-dialog">{{logText}}</pre><template #footer><el-button @click="logOpen=false">关闭</el-button></template></el-dialog>
</div></template>

<style scoped>
.danger-value{color:#b42318}.overview-note{display:grid;grid-template-columns:repeat(3,1fr);padding:18px}.overview-note>div{padding:12px 18px;border-right:1px solid var(--ds-border-soft)}.overview-note>div:last-child{border-right:0}.overview-note strong,.overview-note span{display:block}.overview-note span{margin-top:6px;color:#98a2b3;font-size:12px}.task-card{overflow:visible}.task-toolbar{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border-bottom:1px solid var(--ds-border-soft)}.task-types{display:flex;gap:4px}.task-types button{border:0;background:transparent;border-radius:5px;padding:7px 12px;color:#667085;font-size:13px}.task-types button.active{background:#edf3ff;color:#2f6fed;font-weight:600}.task-table .op-col{width:270px}.task-name{font-weight:600;color:#24364b}.task-table small{display:block;margin-top:3px;color:#98a2b3}.task-actions{white-space:nowrap;overflow:visible!important}.task-actions :deep(.el-button+.el-button){margin-left:8px}.lifecycle{font-size:12px}.lifecycle.online,.lifecycle.published{color:#178354}.lifecycle.offline,.lifecycle.draft{color:#8a93a0}.error-cell{max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.detail-grid{display:grid;grid-template-columns:1fr 1fr;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden}.detail-grid>div{padding:13px 15px;min-height:68px;border-right:1px solid #eef1f5;border-bottom:1px solid #eef1f5}.detail-grid>div:nth-child(2n){border-right:0}.detail-grid span,.detail-grid strong{display:block}.detail-grid span{font-size:12px;color:#98a2b3}.detail-grid strong{margin-top:6px;font-size:13px;color:#344054;word-break:break-all}.detail-error{margin-top:14px;padding:12px;border-radius:7px;background:#fff3f2;color:#b42318;font-size:12px}.readonly-tip{margin-top:16px;padding:11px 12px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:7px;color:#667085;font-size:12px}.log-dialog{min-height:420px;max-height:65vh;overflow:auto;margin:0;padding:14px;background:#0f172a;color:#dbeafe;border-radius:7px;font:12px/1.7 Consolas,monospace;white-space:pre-wrap}
</style>
