<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { formatDateTime } from '../../utils/display'
import { releaseApi, type ReleasePolicy, type ReleaseRecord, type ReleaseRequestView } from '../../api/domain'
const route=useRoute();const loading=ref(true);const policy=ref<ReleasePolicy|null>(null),requests=ref<ReleaseRequestView[]>([]),records=ref<ReleaseRecord[]>([])
const mode=computed(()=>route.path.split('/').pop()||'history')
const title=computed(()=>mode.value==='history'?'发布记录':mode.value==='queue'?'审批队列':'发布策略')
const subtitle=computed(()=>mode.value==='history'?'查看所有进入生产环境的版本和结果。':mode.value==='queue'?'仅在开启人工审批后产生待审核发布。':'人工审批默认关闭；关闭后系统自动审批通过并保留完整发布记录。')
async function load(){loading.value=true;try{policy.value=await releaseApi.policy();if(mode.value==='history')records.value=await releaseApi.records();if(mode.value==='queue')requests.value=await releaseApi.requests('PENDING_APPROVAL')}catch(e){ElMessage.error(e instanceof Error?e.message:'发布中心加载失败')}finally{loading.value=false}}
async function toggle(v:boolean){try{policy.value=await releaseApi.updatePolicy(v);ElMessage.success(v?'人工审批已开启':'人工审批已关闭，后续发布自动审批通过')}catch(e){ElMessage.error(e instanceof Error?e.message:'更新失败')}}
async function approve(r:ReleaseRequestView){try{const comment=await ElMessageBox.prompt('可填写审批意见','审批通过',{confirmButtonText:'通过',cancelButtonText:'取消',inputType:'textarea'});await releaseApi.approve(r.id,comment.value||'');ElMessage.success('已审批并发布');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'审批失败')}}
async function reject(r:ReleaseRequestView){try{const comment=await ElMessageBox.prompt('请输入驳回原因','驳回发布',{confirmButtonText:'驳回',cancelButtonText:'取消',inputValidator:v=>!!String(v||'').trim()||'请填写驳回原因'});await releaseApi.reject(r.id,comment.value||'');ElMessage.success('已驳回');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'驳回失败')}}
function fmt(v?:string){return formatDateTime(v)}
watch(()=>route.path,load);onMounted(load)
</script><template><div class="ds-page"><PageHeader :title="title" :subtitle="subtitle"/><el-skeleton v-if="loading" :rows="7" animated/>
<div v-else-if="mode==='history'" class="ds-card"><div class="ds-toolbar"><strong>生产发布记录</strong><div class="ds-spacer"/><span class="policy-tip">{{policy?.approvalRequired?'人工审批已开启':'自动审批'}}</span></div><div v-if="!records.length" class="ds-empty"><div><div class="ds-empty__title">暂无发布记录</div></div></div><table v-else class="ds-table"><thead><tr><th>资源</th><th>类型</th><th>版本</th><th>结果</th><th>发布人</th><th>发布时间</th><th>详情</th></tr></thead><tbody><tr v-for="r in records" :key="r.id"><td class="ds-resource">{{r.resourceName||`${r.resourceType} #${r.resourceId}`}}</td><td>{{r.resourceType}}</td><td>{{r.releasedVersion?`V${r.releasedVersion}`:'—'}}</td><td><StatusBadge :status="r.resultStatus"/></td><td>{{r.operatorName}}</td><td>{{fmt(r.releasedAt)}}</td><td :title="r.detail">{{r.detail||'—'}}</td></tr></tbody></table></div>
<div v-else-if="mode==='queue'" class="ds-card"><div v-if="!policy?.approvalRequired" class="ds-empty"><div><div class="ds-empty__title">当前不需要人工审批</div><div>有发布权限的用户执行发布后，系统自动审批通过并直接创建生产版本。</div></div></div><div v-else-if="!requests.length" class="ds-empty"><div><div class="ds-empty__title">暂无待审核发布</div></div></div><table v-else class="ds-table"><thead><tr><th>资源</th><th>类型</th><th>目标版本</th><th>提交人</th><th>提交时间</th><th>操作</th></tr></thead><tbody><tr v-for="r in requests" :key="r.id"><td class="ds-resource">{{r.resourceName}}</td><td>{{r.resourceType}}</td><td>{{r.requestedVersion?`V${r.requestedVersion}`:'—'}}</td><td>{{r.requestedBy}}</td><td>{{fmt(r.requestedAt)}}</td><td><span class="ds-link" @click="approve(r)">通过</span><span class="sep">·</span><span class="danger" @click="reject(r)">驳回</span></td></tr></tbody></table></div>
<div v-else class="ds-card policy-card"><div class="policy-row"><div><strong>需要人工审批</strong><p>默认关闭。关闭后，有发布权限的用户点击发布时系统自动审批通过并立即发布。</p></div><el-switch :model-value="policy?.approvalRequired||false" @change="(v:any)=>toggle(Boolean(v))"/></div><div class="audit-note">无论是否开启人工审批，生产发布都会记录资源、版本、发布人、时间和执行结果。关闭审批不等于关闭审计。</div></div>
</div></template><style scoped>.sep{margin:0 7px;color:#d0d5dd}.danger{color:#d92d20;cursor:pointer}.policy-tip{font-size:11px;color:#667085}.policy-card{max-width:820px}.policy-row{display:flex;align-items:center;justify-content:space-between;padding:22px}.policy-row strong{font-size:14px}.policy-row p{margin:6px 0 0;color:#667085;font-size:12px}.audit-note{margin:0 22px 22px;padding:12px;border:1px solid #e4e7ec;border-radius:7px;background:#f9fafb;color:#667085;font-size:12px;line-height:1.6}</style>