<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { dataSourceApi, type DataSourceView } from '../../api/platform'
import { metricApi, type DimensionView, type MetricLineage, type MetricOverview, type MetricView } from '../../api/domain'
const route=useRoute();const loading=ref(true),dialog=ref(false),dimensionDialog=ref(false),saving=ref(false)
const overview=ref<MetricOverview|null>(null),rows=ref<MetricView[]>([]),dimensions=ref<DimensionView[]>([]),lineage=ref<MetricLineage[]>([]),sources=ref<DataSourceView[]>([])
const editingId=ref<number|null>(null),dimensionId=ref<number|null>(null)
const form=reactive<any>({metricCode:'',metricName:'',metricType:'ATOMIC',description:'',businessDomain:'',ownerName:'',sourceDataSourceId:undefined,sourceDatabase:'',sourceTable:'',sourceField:'',aggregation:'SUM',filterExpression:'',timeField:'',expressionText:'',dimensionIds:[],upstreamMetricCodes:[]})
const dim=reactive<any>({dimensionCode:'',dimensionName:'',description:'',sourceDataSourceId:undefined,sourceDatabase:'',sourceTable:'',sourceField:'',ownerName:''})
const mode=computed(()=>route.path.split('/').pop()||'overview')
const title=computed(()=>({overview:'指标总览',manage:'指标管理',dimensions:'维度管理',lineage:'指标血缘'} as any)[mode.value])
const subtitle=computed(()=>mode.value==='overview'?'查看指标建设和认证状态。':mode.value==='manage'?'管理原子、派生和复合指标。':mode.value==='dimensions'?'维护可复用的公共分析维度。':'查看字段、指标及消费关系。')
async function load(){loading.value=true;try{if(mode.value==='overview')overview.value=await metricApi.overview();if(mode.value==='manage'){rows.value=await metricApi.list();sources.value=await dataSourceApi.list();dimensions.value=await metricApi.dimensions()}if(mode.value==='dimensions'){dimensions.value=await metricApi.dimensions();sources.value=await dataSourceApi.list()}if(mode.value==='lineage')lineage.value=await metricApi.lineage()}catch(e){ElMessage.error(e instanceof Error?e.message:'指标中心加载失败')}finally{loading.value=false}}
function openMetric(r?:MetricView){editingId.value=r?.id||null;Object.assign(form,r?{...r,dimensionIds:r.dimensions.map(x=>x.id),upstreamMetricCodes:[]}:{metricCode:'',metricName:'',metricType:'ATOMIC',description:'',businessDomain:'',ownerName:'',sourceDataSourceId:undefined,sourceDatabase:'',sourceTable:'',sourceField:'',aggregation:'SUM',filterExpression:'',timeField:'',expressionText:'',dimensionIds:[],upstreamMetricCodes:[]});dialog.value=true}
async function saveMetric(){if(!form.metricCode||!form.metricName)return ElMessage.warning('请填写指标编码和名称');saving.value=true;try{editingId.value?await metricApi.update(editingId.value,{...form}):await metricApi.create({...form});ElMessage.success('指标草稿已保存');dialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{saving.value=false}}
async function certify(r:MetricView){try{if(r.status==='CERTIFIED')await metricApi.uncertify(r.id);else await metricApi.certify(r.id);ElMessage.success(r.status==='CERTIFIED'?'认证已取消':'指标已认证');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'操作失败')}}
async function removeMetric(r:MetricView){try{await ElMessageBox.confirm(`删除指标“${r.metricName}”？`,'删除指标',{type:'warning'});await metricApi.remove(r.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'删除失败')}}
function openDim(r?:DimensionView){dimensionId.value=r?.id||null;Object.assign(dim,r?{...r}:{dimensionCode:'',dimensionName:'',description:'',sourceDataSourceId:undefined,sourceDatabase:'',sourceTable:'',sourceField:'',ownerName:''});dimensionDialog.value=true}
async function saveDim(){try{dimensionId.value?await metricApi.updateDimension(dimensionId.value,{...dim}):await metricApi.createDimension({...dim});ElMessage.success('维度已保存');dimensionDialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}}
async function removeDim(r:DimensionView){try{await ElMessageBox.confirm(`删除维度“${r.dimensionName}”？`,'删除维度',{type:'warning'});await metricApi.removeDimension(r.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'删除失败')}}
watch(()=>route.path,load);onMounted(load)
</script><template><div class="ds-page"><PageHeader :title="title" :subtitle="subtitle"><template #actions><el-button v-if="mode==='manage'" type="primary" @click="openMetric()">+ 新建指标</el-button><el-button v-if="mode==='dimensions'" type="primary" @click="openDim()">+ 新建维度</el-button></template></PageHeader><el-skeleton v-if="loading" :rows="7" animated/>
<template v-else-if="mode==='overview'&&overview"><div class="ds-grid-4"><div class="ds-card ds-metric"><div class="ds-metric__label">指标总数</div><div class="ds-metric__value">{{overview.total}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">已认证</div><div class="ds-metric__value">{{overview.certified}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">草稿</div><div class="ds-metric__value">{{overview.draft}}</div></div><div class="ds-card ds-metric"><div class="ds-metric__label">公共维度</div><div class="ds-metric__value">{{overview.dimensions}}</div></div></div><div class="ds-card ds-section-gap"><div class="ds-card__head"><div><div class="ds-card__title">指标治理原则</div><div class="ds-card__sub">指标认证与生产发布审批是不同概念。</div></div></div><div class="principles"><span>认证：确认指标定义可被业务复用</span><span>版本：每次修改保存独立定义版本</span><span>血缘：记录上游字段 / 指标关系</span></div></div></template>
<div v-else-if="mode==='manage'" class="ds-card"><div v-if="!rows.length" class="ds-empty"><div><div class="ds-empty__title">暂无指标</div></div></div><table v-else class="ds-table"><thead><tr><th>指标</th><th>类型</th><th>业务域</th><th>Owner</th><th>状态</th><th>版本</th><th>来源</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><span class="ds-resource">{{r.metricName}}</span><div class="sub">{{r.metricCode}}</div></td><td>{{r.metricType}}</td><td>{{r.businessDomain||'—'}}</td><td>{{r.ownerName||'—'}}</td><td><StatusBadge :status="r.status"/></td><td>V{{r.currentVersion}}</td><td>{{[r.sourceDatabase,r.sourceTable,r.sourceField].filter(Boolean).join('.')||r.expressionText||'—'}}</td><td><span class="ds-link" @click="openMetric(r)">编辑</span><span class="sep">·</span><span class="ds-link" @click="certify(r)">{{r.status==='CERTIFIED'?'取消认证':'认证'}}</span><span class="sep">·</span><span class="danger" @click="removeMetric(r)">删除</span></td></tr></tbody></table></div>
<div v-else-if="mode==='dimensions'" class="ds-card"><div v-if="!dimensions.length" class="ds-empty"><div><div class="ds-empty__title">暂无公共维度</div></div></div><table v-else class="ds-table"><thead><tr><th>维度</th><th>编码</th><th>来源字段</th><th>Owner</th><th>操作</th></tr></thead><tbody><tr v-for="r in dimensions" :key="r.id"><td class="ds-resource">{{r.dimensionName}}</td><td>{{r.dimensionCode}}</td><td>{{[r.sourceDatabase,r.sourceTable,r.sourceField].filter(Boolean).join('.')||'—'}}</td><td>{{r.ownerName||'—'}}</td><td><span class="ds-link" @click="openDim(r)">编辑</span><span class="sep">·</span><span class="danger" @click="removeDim(r)">删除</span></td></tr></tbody></table></div>
<div v-else class="ds-card"><div v-if="!lineage.length" class="ds-empty"><div><div class="ds-empty__title">暂无指标血缘</div><div>指标引用来源字段或上游指标后会记录关系。</div></div></div><table v-else class="ds-table"><thead><tr><th>指标</th><th>上游类型</th><th>上游</th><th>下游类型</th><th>下游</th></tr></thead><tbody><tr v-for="r in lineage" :key="r.id"><td><span class="ds-resource">{{r.metricName}}</span><div class="sub">{{r.metricCode}}</div></td><td>{{r.upstreamType}}</td><td>{{r.upstreamRef}}</td><td>{{r.downstreamType||'—'}}</td><td>{{r.downstreamRef||'—'}}</td></tr></tbody></table></div>
<el-dialog v-model="dialog" :title="editingId?'编辑指标':'新建指标'" width="760px"><el-form label-position="top"><div class="two"><el-form-item label="指标编码"><el-input v-model="form.metricCode"/></el-form-item><el-form-item label="指标名称"><el-input v-model="form.metricName"/></el-form-item><el-form-item label="指标类型"><el-select v-model="form.metricType" style="width:100%"><el-option label="原子指标" value="ATOMIC"/><el-option label="派生指标" value="DERIVED"/><el-option label="复合指标" value="COMPOSITE"/></el-select></el-form-item><el-form-item label="业务域"><el-input v-model="form.businessDomain"/></el-form-item><el-form-item label="Owner"><el-input v-model="form.ownerName"/></el-form-item><el-form-item label="聚合"><el-select v-model="form.aggregation" style="width:100%"><el-option label="SUM" value="SUM"/><el-option label="COUNT" value="COUNT"/><el-option label="AVG" value="AVG"/><el-option label="MAX" value="MAX"/><el-option label="MIN" value="MIN"/></el-select></el-form-item><el-form-item label="来源数据源"><el-select v-model="form.sourceDataSourceId" style="width:100%" clearable><el-option v-for="s in sources" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="来源数据库"><el-input v-model="form.sourceDatabase"/></el-form-item><el-form-item label="来源表"><el-input v-model="form.sourceTable"/></el-form-item><el-form-item label="来源字段"><el-input v-model="form.sourceField"/></el-form-item><el-form-item label="时间字段"><el-input v-model="form.timeField"/></el-form-item><el-form-item label="公共维度"><el-select v-model="form.dimensionIds" multiple style="width:100%"><el-option v-for="d in dimensions" :key="d.id" :label="d.dimensionName" :value="d.id"/></el-select></el-form-item></div><el-form-item label="复合/派生表达式"><el-input v-model="form.expressionText" type="textarea" :rows="3"/></el-form-item><el-form-item label="过滤条件"><el-input v-model="form.filterExpression"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea" :rows="2"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveMetric">保存草稿</el-button></template></el-dialog>
<el-dialog v-model="dimensionDialog" :title="dimensionId?'编辑维度':'新建维度'" width="620px"><el-form label-position="top"><div class="two"><el-form-item label="维度编码"><el-input v-model="dim.dimensionCode"/></el-form-item><el-form-item label="维度名称"><el-input v-model="dim.dimensionName"/></el-form-item><el-form-item label="来源数据源"><el-select v-model="dim.sourceDataSourceId" style="width:100%" clearable><el-option v-for="s in sources" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="来源数据库"><el-input v-model="dim.sourceDatabase"/></el-form-item><el-form-item label="来源表"><el-input v-model="dim.sourceTable"/></el-form-item><el-form-item label="来源字段"><el-input v-model="dim.sourceField"/></el-form-item><el-form-item label="Owner"><el-input v-model="dim.ownerName"/></el-form-item></div><el-form-item label="描述"><el-input v-model="dim.description"/></el-form-item></el-form><template #footer><el-button @click="dimensionDialog=false">取消</el-button><el-button type="primary" @click="saveDim">保存</el-button></template></el-dialog></div></template>
<style scoped>.two{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.sub{font-size:10px;color:#98a2b3;margin-top:3px}.sep{margin:0 7px;color:#d0d5dd}.danger{color:#d92d20;cursor:pointer}.principles{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:18px}.principles span{padding:13px;border:1px solid var(--ds-border-soft);border-radius:7px;color:#667085;font-size:12px}

/* DataSphere light product theme — visual overrides only */
.ds-page{padding-top:28px;padding-bottom:36px;background:linear-gradient(180deg,#fbfdff 0%,#f8fbff 100%)}
.ds-grid-4>.ds-card,.ds-page>.ds-card{border:1px solid #e4ebf5;border-radius:16px;background:rgba(255,255,255,.97);box-shadow:0 10px 30px rgba(42,83,163,.04);overflow:hidden}
.ds-grid-4>.ds-card{position:relative;min-height:132px;padding:20px}.ds-grid-4>.ds-card:before{content:'';position:absolute;left:0;top:22px;bottom:22px;width:3px;border-radius:0 3px 3px 0;background:#dbe9ff}.ds-grid-4>.ds-card:nth-child(2):before{background:#bfe8d1}.ds-grid-4>.ds-card:nth-child(3):before{background:#f7d9a7}.ds-grid-4>.ds-card:nth-child(4):before{background:#d8dcff}
.ds-page :deep(.ds-metric__label){color:#78889f;font-size:12px}.ds-page :deep(.ds-metric__value){margin-top:10px;color:#102847;font-size:32px;font-weight:750;letter-spacing:-.5px}
.principles{gap:14px;padding:20px}.principles span{min-height:72px;padding:16px;border:1px solid #e3eaf4;border-radius:12px;background:linear-gradient(180deg,#fff 0%,#f9fbfe 100%);color:#5f7188;font-size:12px;line-height:1.65;box-shadow:0 5px 16px rgba(42,83,163,.025)}
.ds-page>.ds-card :deep(.ds-card__head){border-bottom:1px solid #edf1f6;background:#fff}.ds-page>.ds-card :deep(.ds-card__title){color:#17304f}.ds-page>.ds-card :deep(.ds-card__sub){color:#8493a8}
.ds-page :deep(.ds-table){background:#fff}.ds-page :deep(.ds-table thead th){background:#fbfcfe;color:#78889f;border-bottom-color:#e9eef5;font-size:11px;font-weight:650}.ds-page :deep(.ds-table tbody td){border-bottom-color:#f0f3f7;color:#42566f}.ds-page :deep(.ds-table tbody tr:hover td){background:#f7faff}.ds-resource{color:#2468d8!important;font-weight:650}.sub{color:#8b99ad}.sep{color:#cbd5e1}.danger{color:#e05252}
:deep(.el-dialog){border-radius:16px;overflow:hidden;box-shadow:0 24px 64px rgba(30,60,110,.16)}:deep(.el-dialog__header){margin:0;padding:18px 22px 14px;border-bottom:1px solid #edf1f6;background:#fff}:deep(.el-dialog__body){padding:18px 22px;background:#fbfdff}:deep(.el-dialog__footer){padding:12px 20px 16px;background:#fff;border-top:1px solid #edf1f6}:deep(.el-input__wrapper),:deep(.el-select__wrapper),:deep(.el-textarea__inner){border-radius:8px;box-shadow:0 0 0 1px #dfe8f3 inset}
@media(max-width:1100px){.principles{grid-template-columns:1fr}.two{grid-template-columns:1fr}}

</style>