<script setup lang="ts">
import { onMounted, ref } from 'vue'
import PageHeader from '../../components/PageHeader.vue'
import { developmentApi, type DevFile, type DevProject, type FileVersion } from '../../api/domain'
const projects=ref<DevProject[]>([]), files=ref<DevFile[]>([]), versions=ref<FileVersion[]>([]), projectId=ref<number>(), selected=ref<DevFile>(), loading=ref(false)
async function boot(){projects.value=await developmentApi.projects();if(projects.value[0]){projectId.value=projects.value[0].id;await loadFiles()}}
async function loadFiles(){if(!projectId.value)return;files.value=await developmentApi.files(projectId.value);if(files.value[0])await select(files.value[0])}
async function select(file:DevFile){selected.value=file;loading.value=true;try{versions.value=await developmentApi.versions(file.id)}finally{loading.value=false}}
onMounted(boot)
</script>
<template><div class="ds-page"><PageHeader title="历史版本" subtitle="查看 SQL 文件保存产生的真实版本与发布状态。"/><div class="version-grid"><div class="ds-card"><div class="ds-toolbar"><el-select v-model="projectId" style="width:100%" @change="loadFiles"><el-option v-for="p in projects" :key="p.id" :label="p.name" :value="p.id"/></el-select></div><button v-for="f in files" :key="f.id" class="file-row" :class="{active:selected?.id===f.id}" @click="select(f)"><strong>{{f.name}}</strong><small>当前 V{{f.currentVersion}}</small></button></div><div class="ds-card"><div class="ds-card__head"><div><div class="ds-card__title">{{selected?.name||'文件版本'}}</div><div class="ds-card__sub">每次保存都会生成版本，工作流绑定固定版本快照。</div></div></div><el-table :data="versions" v-loading="loading"><el-table-column prop="versionNo" label="版本" width="100"><template #default="s">V{{s.row.versionNo}}</template></el-table-column><el-table-column prop="checksum" label="Checksum" min-width="180" show-overflow-tooltip/><el-table-column label="状态" width="120"><template #default="s"><el-tag :type="s.row.publishFlag?'success':'info'">{{s.row.publishFlag?'已发布':'历史版本'}}</el-tag></template></el-table-column><el-table-column label="内容" min-width="320"><template #default="s"><code>{{s.row.content}}</code></template></el-table-column></el-table></div></div></div></template>
<style scoped>.version-grid{display:grid;grid-template-columns:260px minmax(0,1fr);gap:12px}.file-row{display:flex;flex-direction:column;width:100%;border:0;border-top:1px solid var(--ds-border-soft);background:#fff;padding:11px 14px;text-align:left;cursor:pointer}.file-row.active{background:var(--ds-brand-soft);color:var(--ds-brand)}.file-row small{margin-top:4px;color:var(--ds-text-tertiary)}code{font-size:11px;white-space:nowrap}</style>
