<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import * as monaco from 'monaco-editor'
import { ElMessage } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import { dataSourceApi } from '../../api/platform'
import { developmentApi, metadataApi, releaseApi, type DataSourceView, type DevFile, type DevProject, type QueryResult, type TableView } from '../../api/domain'

const projects=ref<DevProject[]>([]), files=ref<DevFile[]>([]), sources=ref<DataSourceView[]>([]), databases=ref<string[]>([]), tables=ref<TableView[]>([])
const projectId=ref<number>(), file=ref<DevFile>(), sourceId=ref<number>(), database=ref(''), result=ref<QueryResult>(), activeBottom=ref('result'), saving=ref(false), running=ref(false), loading=ref(false)
const editorHost=ref<HTMLElement>(), editor=ref<monaco.editor.IStandaloneCodeEditor>(), output=ref('')

async function boot(){loading.value=true;try{projects.value=await developmentApi.projects();sources.value=(await dataSourceApi.list()).filter(s=>s.type==='STARROCKS');if(projects.value[0]){projectId.value=projects.value[0].id;await loadFiles()}if(sources.value[0]){sourceId.value=sources.value[0].id;await loadDatabases()}await nextTick();initEditor()}catch(e){ElMessage.error(msg(e))}finally{loading.value=false}}
function initEditor(){if(!editorHost.value||editor.value)return;editor.value=monaco.editor.create(editorHost.value,{value:file.value?.content||'-- 选择或新建 SQL 文件\nSELECT 1;',language:'sql',theme:'vs',automaticLayout:true,minimap:{enabled:false},fontSize:13,lineHeight:22,scrollBeyondLastLine:false});editor.value.onDidChangeModelContent(()=>{if(file.value)file.value={...file.value,content:editor.value?.getValue()||''}})}
async function loadFiles(){if(!projectId.value)return;files.value=await developmentApi.files(projectId.value);if(files.value[0])await openFile(files.value[0])}
async function openFile(row:DevFile){file.value=await developmentApi.getFile(row.id);editor.value?.setValue(file.value.content||'')}
async function newFile(){if(!projectId.value)return;const created=await developmentApi.createFile({projectId:projectId.value,name:`query_${Date.now()}.sql`,fileType:'SQL',content:'SELECT 1;',description:'DataSphere SQL 开发文件'});files.value=await developmentApi.files(projectId.value);await openFile(created);ElMessage.success('SQL 文件已创建')}
async function publish(){if(!file.value)return ElMessage.warning('请选择 SQL 文件');try{await releaseApi.request({resourceType:'DEVELOPMENT',resourceId:file.value.id,resourceName:file.value.name,requestedVersion:file.value.currentVersion});ElMessage.success('发布请求已处理')}catch(e){ElMessage.error(msg(e))}}
async function save(){if(!file.value||!editor.value)return;saving.value=true;try{file.value=await developmentApi.saveFile(file.value.id,{content:editor.value.getValue(),name:file.value.name,description:file.value.description});files.value=await developmentApi.files(file.value.projectId);ElMessage.success(`已保存版本 V${file.value.currentVersion}`)}catch(e){ElMessage.error(msg(e))}finally{saving.value=false}}
async function run(explain=false){if(!sourceId.value||!editor.value)return ElMessage.warning('请选择 StarRocks 数据源');running.value=true;activeBottom.value='result';try{const sql=editor.value.getModel()?.getValueInRange(editor.value.getSelection()||editor.value.getModel()!.getFullModelRange())||editor.value.getValue();result.value=await developmentApi.query(explain?`EXPLAIN ${sql}`:sql,sourceId.value,database.value||undefined);output.value=`${result.value.status} · ${result.value.rowCount} 行 · ${result.value.elapsedMs} ms`}catch(e){output.value=msg(e);ElMessage.error(output.value)}finally{running.value=false}}
async function loadDatabases(){if(!sourceId.value)return;const rows=await metadataApi.databases(sourceId.value,'STARROCKS');databases.value=rows.map(x=>x.name);database.value=databases.value[0]||'';await loadTables()}
async function loadTables(){if(!sourceId.value||!database.value)return;tables.value=await metadataApi.tables(sourceId.value,database.value)}
function insertTable(name:string){const ed=editor.value;if(!ed)return;const sel=ed.getSelection();if(sel)ed.executeEdits('metadata',[{range:sel,text:`\`${database.value}\`.\`${name}\``,forceMoveMarkers:true}]);ed.focus()}
function format(){editor.value?.getAction('editor.action.formatDocument')?.run()}
function msg(e:unknown){return e instanceof Error?e.message:'操作失败'}
watch(projectId,loadFiles);watch(sourceId,loadDatabases);watch(database,loadTables)
onMounted(boot);onBeforeUnmount(()=>editor.value?.dispose())
</script>
<template>
<div class="dev-page" v-loading="loading">
  <div class="dev-toolbar"><PageHeader title="SQL 开发" subtitle="StarRocks SQL 开发、执行、EXPLAIN 与版本保存。"><template #actions><el-button @click="format">格式化</el-button><el-button @click="run(true)">EXPLAIN</el-button><el-button :loading="running" @click="run(false)">运行</el-button><el-button :loading="saving" @click="save">保存版本</el-button><el-button type="primary" @click="publish">发布</el-button></template></PageHeader></div>
  <div class="ide-grid">
    <aside class="resource-panel"><div class="panel-title">研发资源 <el-button link type="primary" @click="newFile">+ SQL</el-button></div><el-select v-model="projectId" style="width:100%"><el-option v-for="p in projects" :key="p.id" :label="p.name" :value="p.id"/></el-select><div class="file-list"><button v-for="f in files" :key="f.id" :class="{active:file?.id===f.id}" @click="openFile(f)"><span>SQL</span><div><strong>{{f.name}}</strong><small>V{{f.currentVersion}} · {{f.status}}</small></div></button></div></aside>
    <main class="editor-panel"><div class="editor-top"><strong>{{file?.name||'未选择文件'}}</strong><span v-if="file">V{{file.currentVersion}}</span><div class="ds-spacer"/><el-select v-model="sourceId" placeholder="StarRocks" style="width:170px"><el-option v-for="s in sources" :key="s.id" :label="s.name" :value="s.id"/></el-select><el-select v-model="database" placeholder="Database" style="width:150px"><el-option v-for="d in databases" :key="d" :label="d" :value="d"/></el-select></div><div ref="editorHost" class="editor-host"/><section class="result-panel"><el-tabs v-model="activeBottom"><el-tab-pane label="结果" name="result"><div class="result-meta">{{output||'运行 SQL 后在这里查看结果'}}</div><el-table v-if="result?.rows?.length" :data="result.rows" height="230" border><el-table-column v-for="c in result.columns" :key="c" :prop="c" :label="c" min-width="130" show-overflow-tooltip/></el-table><div v-else class="ds-empty small">暂无结果</div></el-tab-pane><el-tab-pane label="日志" name="log"><pre class="log">{{output||'暂无执行日志'}}</pre></el-tab-pane></el-tabs></section></main>
    <aside class="metadata-panel"><div class="panel-title">对象信息</div><div class="meta-caption">{{database||'未选择数据库'}} · {{tables.length}} 张表</div><div class="meta-tables"><button v-for="t in tables" :key="t.name" @dblclick="insertTable(t.name)"><strong>{{t.name}}</strong><small>{{t.comment||'双击插入表名'}}</small></button></div></aside>
  </div>
</div>
</template>
<style scoped>
.dev-page{height:calc(100vh - var(--ds-topbar));display:flex;flex-direction:column;min-height:720px}.dev-toolbar{padding:18px 22px 0}.dev-toolbar :deep(.ds-page-header){margin-bottom:14px}.ide-grid{flex:1;min-height:0;display:grid;grid-template-columns:250px minmax(650px,1fr) 280px;border-top:1px solid var(--ds-border);background:#fff}.resource-panel,.metadata-panel{padding:14px;border-right:1px solid var(--ds-border);overflow:auto}.metadata-panel{border-right:0;border-left:1px solid var(--ds-border)}.panel-title{height:34px;display:flex;align-items:center;justify-content:space-between;font-weight:650}.file-list,.meta-tables{display:flex;flex-direction:column;gap:3px;margin-top:10px}.file-list button,.meta-tables button{display:flex;gap:8px;border:0;background:transparent;border-radius:6px;padding:8px;text-align:left;cursor:pointer;color:#475467}.file-list button.active{background:var(--ds-brand-soft);color:var(--ds-brand)}.file-list button>span{font-size:9px;border:1px solid #d0d5dd;border-radius:3px;padding:2px;height:20px}.file-list strong,.file-list small,.meta-tables strong,.meta-tables small{display:block}.file-list small,.meta-tables small,.meta-caption{color:var(--ds-text-tertiary);font-size:10px;margin-top:2px}.editor-panel{min-width:0;display:grid;grid-template-rows:45px minmax(260px,1fr) 300px}.editor-top{display:flex;align-items:center;gap:10px;padding:0 12px;border-bottom:1px solid var(--ds-border)}.editor-top>span{font-size:10px;color:var(--ds-text-tertiary)}.editor-host{min-height:0}.result-panel{min-height:0;border-top:1px solid var(--ds-border);padding:0 12px;overflow:hidden}.result-meta{font-size:11px;color:var(--ds-text-tertiary);padding:0 0 8px}.ds-empty.small{min-height:130px}.log{white-space:pre-wrap;font-size:11px;color:#475467}.meta-tables button{display:block;border-bottom:1px solid var(--ds-border-soft);border-radius:0}.meta-tables button:hover{background:#fafbff}
</style>
