<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { flinkApi, seaTunnelEnvironmentApi, type FlinkEnvironment, type SeaTunnelEnvironment } from '../../api/domain'
import { formatDateTime } from '../../utils/display'

const activeTab=ref<'flink'|'seatunnel'>('flink')
const loading=ref(true), flinkRows=ref<FlinkEnvironment[]>([]), seaTunnelRows=ref<SeaTunnelEnvironment[]>([])
const flinkDialog=ref(false), seaTunnelDialog=ref(false), editingFlinkId=ref<number|null>(null), editingSeaTunnelId=ref<number|null>(null)
const testingFlink=ref<number|null>(null), testingSeaTunnel=ref<number|null>(null)
const flinkForm=reactive<any>({name:'',submitterType:'SSH',restUrl:'http://127.0.0.1:8081',flinkHome:'/data/software/flink',flinkCdcHome:'/data/software/flink-cdc',javaHome:'',sshHost:'',sshPort:22,sshUsername:'',sshPassword:'',enabled:true,defaultEnvironment:false})
const seaTunnelForm=reactive<any>({name:'',host:'',port:8030,sshUsername:'root',sshPort:22,sshPassword:'',seatunnelHome:'/data/software/seatunnel',description:''})
const actionTitle=computed(()=>activeTab.value==='flink'?'+ 新建 Flink 环境':'+ 新建 SeaTunnel 环境')

async function load(){loading.value=true;try{[flinkRows.value,seaTunnelRows.value]=await Promise.all([flinkApi.list(),seaTunnelEnvironmentApi.list()])}catch(e){ElMessage.error(e instanceof Error?e.message:'运行环境加载失败')}finally{loading.value=false}}
function resetFlink(){editingFlinkId.value=null;Object.assign(flinkForm,{name:'',submitterType:'SSH',restUrl:'http://127.0.0.1:8081',flinkHome:'/data/software/flink',flinkCdcHome:'/data/software/flink-cdc',javaHome:'',sshHost:'',sshPort:22,sshUsername:'',sshPassword:'',enabled:true,defaultEnvironment:false})}
function openFlink(r?:FlinkEnvironment){resetFlink();if(r){editingFlinkId.value=r.id;Object.assign(flinkForm,{...r,sshPassword:''})}flinkDialog.value=true}
function resetSeaTunnel(){editingSeaTunnelId.value=null;Object.assign(seaTunnelForm,{name:'',host:'',port:8030,sshUsername:'root',sshPort:22,sshPassword:'',seatunnelHome:'/data/software/seatunnel',description:''})}
function openSeaTunnel(r?:SeaTunnelEnvironment){resetSeaTunnel();if(r){editingSeaTunnelId.value=r.id;Object.assign(seaTunnelForm,{...r,sshPassword:''})}seaTunnelDialog.value=true}
function createEnv(){activeTab.value==='flink'?openFlink():openSeaTunnel()}
async function saveFlink(){try{const payload={...flinkForm,deploymentMode:'REMOTE',flinkVersion:'',flinkCdcVersion:''};editingFlinkId.value?await flinkApi.update(editingFlinkId.value,payload):await flinkApi.create(payload);ElMessage.success('Flink 环境已保存');flinkDialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}}
async function saveSeaTunnel(){if(!seaTunnelForm.name?.trim()||!seaTunnelForm.host?.trim()||!seaTunnelForm.seatunnelHome?.trim())return ElMessage.warning('请填写环境名称、主机地址和 SeaTunnel 根目录');if(!editingSeaTunnelId.value&&!seaTunnelForm.sshPassword) return ElMessage.warning('新建环境请填写 SSH 密码');try{editingSeaTunnelId.value?await seaTunnelEnvironmentApi.update(editingSeaTunnelId.value,{...seaTunnelForm}):await seaTunnelEnvironmentApi.create({...seaTunnelForm});ElMessage.success('SeaTunnel 环境已保存');seaTunnelDialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}}
async function testFlink(r:FlinkEnvironment){testingFlink.value=r.id;try{await flinkApi.test(r.id);ElMessage.success('Flink 环境连接正常')}catch(e){ElMessage.error(e instanceof Error?e.message:'连接失败')}finally{testingFlink.value=null}}
async function testSeaTunnel(r:SeaTunnelEnvironment){testingSeaTunnel.value=r.id;try{const next=await seaTunnelEnvironmentApi.check(r.id);Object.assign(r,next);ElMessage.success(next.healthStatus==='HEALTHY'?'SeaTunnel 环境连接正常':'SeaTunnel 环境检查未通过')}catch(e){ElMessage.error(e instanceof Error?e.message:'连接失败')}finally{testingSeaTunnel.value=null}}
async function removeFlink(r:FlinkEnvironment){try{await ElMessageBox.confirm(`删除 Flink 环境“${r.name}”？`,'删除环境',{type:'warning'});await flinkApi.remove(r.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'删除失败')}}
async function removeSeaTunnel(r:SeaTunnelEnvironment){try{await ElMessageBox.confirm(`删除 SeaTunnel 环境“${r.name}”？`,'删除环境',{type:'warning'});await seaTunnelEnvironmentApi.remove(r.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'删除失败')}}
onMounted(load)
</script>

<template><div class="ds-page">
  <PageHeader title="运行环境" subtitle="集中管理实时同步使用的 Flink 环境和离线同步使用的 SeaTunnel 环境。"><template #actions><el-button type="primary" @click="createEnv">{{actionTitle}}</el-button></template></PageHeader>
  <div class="ds-card env-card">
    <el-tabs v-model="activeTab" class="env-tabs">
      <el-tab-pane label="Flink" name="flink">
        <div class="ds-toolbar"><div><strong>Flink 环境</strong><div class="sub">用于独立 Flink CDC 实时同步任务。</div></div><div class="ds-spacer"/><el-button @click="load" :loading="loading">刷新</el-button></div>
        <el-skeleton v-if="loading" :rows="5" animated/><div v-else-if="!flinkRows.length" class="ds-empty"><div><div class="ds-empty__title">暂无 Flink 环境</div><div>新建环境后即可用于实时同步任务。</div></div></div>
        <table v-else class="ds-table"><thead><tr><th>名称</th><th>提交方式</th><th>REST 地址</th><th>Flink Home</th><th>Flink CDC Home</th><th>默认</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="r in flinkRows" :key="r.id"><td class="ds-resource">{{r.name}}</td><td>{{r.submitterType==='SSH'?'SSH / CLI':r.submitterType==='LOCAL'?'本机 CLI':'Flink REST'}}</td><td>{{r.restUrl||'—'}}</td><td>{{r.flinkHome||'—'}}</td><td>{{r.flinkCdcHome||'—'}}</td><td>{{r.defaultEnvironment?'是':'否'}}</td><td><StatusBadge :status="r.enabled?'ACTIVE':'STOPPED'"/></td><td><span class="ds-link" @click="testFlink(r)">{{testingFlink===r.id?'测试中...':'测试'}}</span><span class="sep">·</span><span class="ds-link" @click="openFlink(r)">编辑</span><span class="sep">·</span><span class="danger" @click="removeFlink(r)">删除</span></td></tr></tbody></table>
      </el-tab-pane>
      <el-tab-pane label="SeaTunnel" name="seatunnel">
        <div class="ds-toolbar"><div><strong>SeaTunnel 环境</strong><div class="sub">用于 MySQL → SeaTunnel → StarRocks 离线同步。</div></div><div class="ds-spacer"/><el-button @click="load" :loading="loading">刷新</el-button></div>
        <el-skeleton v-if="loading" :rows="5" animated/><div v-else-if="!seaTunnelRows.length" class="ds-empty"><div><div class="ds-empty__title">暂无 SeaTunnel 环境</div><div>新建环境后平台会通过 SSH 提交离线同步任务。</div></div></div>
        <table v-else class="ds-table"><thead><tr><th>环境名称</th><th>主机地址</th><th>端口</th><th>SSH 用户</th><th>SeaTunnel 根目录</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="r in seaTunnelRows" :key="r.id"><td class="ds-resource">{{r.name}}</td><td>{{r.host}}</td><td>{{r.port}}</td><td>{{r.sshUsername||'—'}}:{{r.sshPort}}</td><td>{{r.seatunnelHome}}</td><td><StatusBadge :status="r.healthStatus"/></td><td>{{formatDateTime(r.createdAt)}}</td><td><span class="ds-link" @click="testSeaTunnel(r)">{{testingSeaTunnel===r.id?'检查中...':'检查'}}</span><span class="sep">·</span><span class="ds-link" @click="openSeaTunnel(r)">编辑</span><span class="sep">·</span><span class="danger" @click="removeSeaTunnel(r)">删除</span></td></tr></tbody></table>
      </el-tab-pane>
    </el-tabs>
  </div>

  <el-dialog v-model="flinkDialog" :title="editingFlinkId?'编辑 Flink 环境':'新建 Flink 环境'" width="680px" destroy-on-close><el-form label-position="top"><div class="two"><el-form-item label="环境名称"><el-input v-model="flinkForm.name" placeholder="例如 flink-prod-01"/></el-form-item><el-form-item label="提交方式"><el-select v-model="flinkForm.submitterType" style="width:100%"><el-option label="SSH / CLI" value="SSH"/><el-option label="Flink REST" value="REST"/><el-option label="本机 CLI" value="LOCAL"/></el-select></el-form-item><el-form-item label="REST 地址"><el-input v-model="flinkForm.restUrl" placeholder="http://127.0.0.1:8081"/></el-form-item><el-form-item label="Flink Home"><el-input v-model="flinkForm.flinkHome" placeholder="/data/software/flink"/></el-form-item><el-form-item label="Flink CDC Home"><el-input v-model="flinkForm.flinkCdcHome" placeholder="/data/software/flink-cdc"/></el-form-item><el-form-item label="Java Home"><el-input v-model="flinkForm.javaHome" placeholder="可选"/></el-form-item><el-form-item label="SSH 主机"><el-input v-model="flinkForm.sshHost" placeholder="IP 或域名"/></el-form-item><el-form-item label="SSH 端口"><el-input-number v-model="flinkForm.sshPort" :min="1" :max="65535" style="width:100%"/></el-form-item><el-form-item label="SSH 用户名"><el-input v-model="flinkForm.sshUsername"/></el-form-item><el-form-item label="SSH 密码（编辑时留空保留原密码）"><el-input v-model="flinkForm.sshPassword" type="password" show-password/></el-form-item></div><el-switch v-model="flinkForm.enabled" active-text="启用"/><el-checkbox v-model="flinkForm.defaultEnvironment">设为默认环境</el-checkbox></el-form><template #footer><el-button @click="flinkDialog=false">取消</el-button><el-button type="primary" @click="saveFlink">保存</el-button></template></el-dialog>

  <el-dialog v-model="seaTunnelDialog" :title="editingSeaTunnelId?'编辑 SeaTunnel 环境':'新建 SeaTunnel 环境'" width="680px" destroy-on-close><el-form label-position="top"><el-form-item label="环境名称"><el-input v-model="seaTunnelForm.name" placeholder="例如 seatunnel-prod-01"/></el-form-item><div class="host-grid"><el-form-item label="主机地址"><el-input v-model="seaTunnelForm.host" placeholder="192.168.1.100"/></el-form-item><el-form-item label="端口"><el-input-number v-model="seaTunnelForm.port" :min="1" :max="65535" style="width:100%"/></el-form-item><el-form-item label="SSH 用户名"><el-input v-model="seaTunnelForm.sshUsername" placeholder="root"/></el-form-item><el-form-item label="SSH 端口"><el-input-number v-model="seaTunnelForm.sshPort" :min="1" :max="65535" style="width:100%"/></el-form-item></div><div class="two"><el-form-item label="SSH 密码（编辑时留空保留原密码）"><el-input v-model="seaTunnelForm.sshPassword" type="password" show-password placeholder="SSH 登录密码"/></el-form-item><el-form-item label="SeaTunnel 根目录"><el-input v-model="seaTunnelForm.seatunnelHome" placeholder="/data/software/seatunnel"/></el-form-item></div><el-form-item label="描述"><el-input v-model="seaTunnelForm.description" type="textarea" :rows="3" placeholder="可选描述"/></el-form-item></el-form><template #footer><el-button @click="seaTunnelDialog=false">取消</el-button><el-button type="primary" @click="saveSeaTunnel">保存</el-button></template></el-dialog>
</div></template>
<style scoped>.env-card{padding:0 16px 16px}.env-tabs :deep(.el-tabs__header){margin:0 0 12px}.ds-toolbar{padding-left:0;padding-right:0}.sub{margin-top:4px;color:var(--ds-text-tertiary);font-size:11px}.two{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.host-grid{display:grid;grid-template-columns:minmax(0,1fr) 180px;gap:0 14px}.sep{margin:0 7px;color:#d0d5dd}.danger{color:#d92d20;cursor:pointer}</style>
