<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { flinkApi, type FlinkEnvironment } from '../../api/domain'
const loading=ref(true),rows=ref<FlinkEnvironment[]>([]),dialog=ref(false),editingId=ref<number|null>(null),testing=ref<number|null>(null)
const form=reactive<any>({name:'',deploymentMode:'STANDALONE',submitterType:'REST',restUrl:'http://127.0.0.1:8081',flinkHome:'/data/software/flink',flinkCdcHome:'/data/software/flink-cdc',javaHome:'',flinkVersion:'1.20.1',flinkCdcVersion:'3.3.0',sshHost:'',sshPort:22,sshUsername:'',sshPassword:'',enabled:true,defaultEnvironment:false})
async function load(){loading.value=true;try{rows.value=await flinkApi.list()}catch(e){ElMessage.error(e instanceof Error?e.message:'环境加载失败')}finally{loading.value=false}}
function open(r?:FlinkEnvironment){editingId.value=r?.id||null;Object.assign(form,r?{...r,sshPassword:''}:{name:'',deploymentMode:'STANDALONE',submitterType:'REST',restUrl:'http://127.0.0.1:8081',flinkHome:'/data/software/flink',flinkCdcHome:'/data/software/flink-cdc',javaHome:'',flinkVersion:'1.20.1',flinkCdcVersion:'3.3.0',sshHost:'',sshPort:22,sshUsername:'',sshPassword:'',enabled:true,defaultEnvironment:false});dialog.value=true}
async function save(){try{editingId.value?await flinkApi.update(editingId.value,{...form}):await flinkApi.create({...form});ElMessage.success('Flink 环境已保存');dialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}}
async function test(r:FlinkEnvironment){testing.value=r.id;try{await flinkApi.test(r.id);ElMessage.success('Flink REST 连接成功')}catch(e){ElMessage.error(e instanceof Error?e.message:'连接失败')}finally{testing.value=null}}
async function remove(r:FlinkEnvironment){try{await ElMessageBox.confirm(`删除运行环境“${r.name}”？`,'删除环境',{type:'warning'});await flinkApi.remove(r.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'删除失败')}}
onMounted(load)
</script><template><div class="ds-page"><PageHeader title="运行环境" subtitle="管理 Flink CDC 运行环境；SeaTunnel 继续使用现有集群配置。"><template #actions><el-button type="primary" @click="open()">+ 新建 Flink 环境</el-button></template></PageHeader><div class="ds-card"><div class="ds-toolbar"><strong>Flink 环境</strong><div class="ds-spacer"/><el-button @click="load">刷新</el-button></div><el-skeleton v-if="loading" :rows="6" animated/><div v-else-if="!rows.length" class="ds-empty"><div><div class="ds-empty__title">暂无 Flink 环境</div><div>实时任务发布前至少需要一个启用的环境。</div></div></div><table v-else class="ds-table"><thead><tr><th>名称</th><th>提交方式</th><th>REST</th><th>Flink</th><th>Flink CDC</th><th>默认</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td class="ds-resource">{{r.name}}</td><td>{{r.submitterType}}</td><td>{{r.restUrl||'—'}}</td><td>{{r.flinkVersion||'—'}}</td><td>{{r.flinkCdcVersion||'—'}}</td><td>{{r.defaultEnvironment?'是':'否'}}</td><td><StatusBadge :status="r.enabled?'ACTIVE':'STOPPED'"/></td><td><span class="ds-link" @click="test(r)">{{testing===r.id?'测试中...':'测试'}}</span><span class="sep">·</span><span class="ds-link" @click="open(r)">编辑</span><span class="sep">·</span><span class="danger" @click="remove(r)">删除</span></td></tr></tbody></table></div>
<el-dialog v-model="dialog" :title="editingId?'编辑 Flink 环境':'新建 Flink 环境'" width="720px"><el-form label-position="top"><div class="two"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="提交方式"><el-select v-model="form.submitterType" style="width:100%"><el-option label="Flink REST" value="REST"/><el-option label="SSH / CLI" value="SSH"/><el-option label="本机 CLI" value="LOCAL"/></el-select></el-form-item><el-form-item label="REST URL"><el-input v-model="form.restUrl"/></el-form-item><el-form-item label="部署模式"><el-input v-model="form.deploymentMode"/></el-form-item><el-form-item label="Flink Home"><el-input v-model="form.flinkHome"/></el-form-item><el-form-item label="Flink CDC Home"><el-input v-model="form.flinkCdcHome"/></el-form-item><el-form-item label="Flink Version"><el-input v-model="form.flinkVersion"/></el-form-item><el-form-item label="Flink CDC Version"><el-input v-model="form.flinkCdcVersion"/></el-form-item><el-form-item label="SSH Host"><el-input v-model="form.sshHost"/></el-form-item><el-form-item label="SSH Port"><el-input-number v-model="form.sshPort" :min="1" :max="65535" style="width:100%"/></el-form-item><el-form-item label="SSH User"><el-input v-model="form.sshUsername"/></el-form-item><el-form-item label="SSH Password（可留空使用平台免密私钥）"><el-input v-model="form.sshPassword" type="password" show-password/></el-form-item></div><el-checkbox v-model="form.enabled">启用</el-checkbox><el-checkbox v-model="form.defaultEnvironment">设为默认环境</el-checkbox></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template><style scoped>.two{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.sep{margin:0 7px;color:#d0d5dd}.danger{color:#d92d20;cursor:pointer}</style>