<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { api } from '../../api/http'
interface User{ id:number;username:string;displayName:string;roleCode:string;status:string;createdAt:string }
interface Role{ id:number;roleCode:string;roleName:string;permissions:string[] }
interface Audit{ id:number;action:string;resourceType:string;resourceId?:number;detail?:string;operatorName:string;createdAt:string }
const route=useRoute(),loading=ref(true),users=ref<User[]>([]),roles=ref<Role[]>([]),audits=ref<Audit[]>([]),dialog=ref(false)
const form=reactive({username:'',displayName:'',password:'',roleCode:'DEVELOPER',status:'ACTIVE'})
const mode=computed(()=>route.path.endsWith('/roles')?'roles':route.path.endsWith('/audit')?'audit':'users')
async function load(){loading.value=true;try{if(mode.value==='users')users.value=await api.get<User[]>('/system/users');if(mode.value==='roles')roles.value=await api.get<Role[]>('/system/roles');if(mode.value==='audit')audits.value=await api.get<Audit[]>('/system/audit-logs')}catch(e){ElMessage.error(e instanceof Error?e.message:'系统数据加载失败')}finally{loading.value=false}}
async function createUser(){try{await api.post('/system/users',{...form});ElMessage.success('用户已创建');dialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'创建失败')}}
async function toggle(u:User){try{await api.post(`/system/users/${u.id}/${u.status==='ACTIVE'?'disable':'enable'}`);await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'操作失败')}}
async function remove(u:User){try{await ElMessageBox.confirm(`删除用户“${u.displayName}”？`,'删除用户',{type:'warning'});await api.delete(`/system/users/${u.id}`);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'删除失败')}}
function fmt(v?:string){return v?v.replace('T',' ').slice(0,16):'—'}
watch(()=>route.path,load);onMounted(load)
</script><template><div class="ds-page"><PageHeader :title="mode==='users'?'用户管理':mode==='roles'?'角色权限':'审计日志'" :subtitle="mode==='users'?'管理公司内部平台用户。':mode==='roles'?'查看角色与权限集合。':'查看关键操作和生产变更记录。'"><template #actions><el-button v-if="mode==='users'" type="primary" @click="dialog=true">+ 新增用户</el-button></template></PageHeader><el-skeleton v-if="loading" :rows="7" animated/><div v-else-if="mode==='users'" class="ds-card"><table class="ds-table"><thead><tr><th>用户</th><th>账号</th><th>角色</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td class="ds-resource">{{u.displayName}}</td><td>{{u.username}}</td><td>{{u.roleCode}}</td><td><StatusBadge :status="u.status"/></td><td>{{fmt(u.createdAt)}}</td><td><span class="ds-link" @click="toggle(u)">{{u.status==='ACTIVE'?'禁用':'启用'}}</span><span class="sep">·</span><span class="danger" @click="remove(u)">删除</span></td></tr></tbody></table></div><div v-else-if="mode==='roles'" class="ds-card"><table class="ds-table"><thead><tr><th>角色</th><th>编码</th><th>权限</th></tr></thead><tbody><tr v-for="r in roles" :key="r.id"><td class="ds-resource">{{r.roleName}}</td><td>{{r.roleCode}}</td><td class="permissions">{{[...(r.permissions||[])].join(' · ')||'—'}}</td></tr></tbody></table></div><div v-else class="ds-card"><table class="ds-table"><thead><tr><th>动作</th><th>资源</th><th>操作人</th><th>详情</th><th>时间</th></tr></thead><tbody><tr v-for="a in audits" :key="a.id"><td>{{a.action}}</td><td>{{a.resourceType}} {{a.resourceId||''}}</td><td>{{a.operatorName}}</td><td>{{a.detail||'—'}}</td><td>{{fmt(a.createdAt)}}</td></tr></tbody></table></div><el-dialog v-model="dialog" title="新增用户" width="520px"><el-form label-position="top"><el-form-item label="账号"><el-input v-model="form.username"/></el-form-item><el-form-item label="显示名称"><el-input v-model="form.displayName"/></el-form-item><el-form-item label="初始密码"><el-input v-model="form.password" type="password" show-password/></el-form-item><el-form-item label="角色"><el-select v-model="form.roleCode" style="width:100%"><el-option v-for="r in roles" :key="r.id" :label="r.roleName" :value="r.roleCode"/><el-option v-if="!roles.length" label="开发者" value="DEVELOPER"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="createUser">创建</el-button></template></el-dialog></div></template><style scoped>.sep{margin:0 7px;color:#d0d5dd}.danger{color:#d92d20;cursor:pointer}.permissions{white-space:normal!important;line-height:1.6}</style>