<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import PageHeader from '../../components/PageHeader.vue'
import { dataSourceApi } from '../../api/platform'
import { metadataApi, type DataSourceView, type DatabaseView, type TableView, type ColumnView, type TableProfile, type LineageView } from '../../api/domain'

const sources=ref<DataSourceView[]>([]), databases=ref<DatabaseView[]>([]), tables=ref<TableView[]>([]), columns=ref<ColumnView[]>([]), lineage=ref<LineageView[]>([])
const sourceId=ref<number>(), database=ref(''), table=ref<TableView>(), profile=ref<TableProfile>(), loading=ref(false), error=ref(''), keyword=ref('')
const filteredTables=computed(()=>tables.value.filter(t=>!keyword.value||`${t.name} ${t.comment||''}`.toLowerCase().includes(keyword.value.toLowerCase())))
async function loadSources(){try{sources.value=(await dataSourceApi.list()).filter(s=>s.metadataVisible);const first=sources.value.find(s=>s.type==='STARROCKS')||sources.value[0];if(first){sourceId.value=first.id;await selectSource(first.id)}}catch(e){error.value=e instanceof Error?e.message:'数据源加载失败'}}
async function selectSource(id:number){sourceId.value=id;database.value='';tables.value=[];columns.value=[];table.value=undefined;loading.value=true;try{const s=sources.value.find(x=>x.id===id);databases.value=await metadataApi.databases(id,s?.type||'STARROCKS');if(databases.value[0])await selectDatabase(databases.value[0].name)}catch(e){error.value=e instanceof Error?e.message:'数据库加载失败'}finally{loading.value=false}}
async function selectDatabase(name:string){if(!sourceId.value)return;database.value=name;table.value=undefined;columns.value=[];profile.value=undefined;lineage.value=[];loading.value=true;try{tables.value=await metadataApi.tables(sourceId.value,name);if(tables.value[0])await selectTable(tables.value[0])}catch(e){error.value=e instanceof Error?e.message:'表加载失败'}finally{loading.value=false}}
async function selectTable(value:TableView){if(!sourceId.value)return;table.value=value;loading.value=true;try{const [cols,prof,lin]=await Promise.all([metadataApi.columns(sourceId.value,database.value,value.name),metadataApi.profile(sourceId.value,database.value,value.name),metadataApi.lineage(`${database.value}.${value.name}`)]);columns.value=cols;profile.value=prof;lineage.value=lin}catch(e){error.value=e instanceof Error?e.message:'表详情加载失败'}finally{loading.value=false}}
function fmtSize(v?:number){if(v==null)return '—';if(v>1024**3)return `${(v/1024**3).toFixed(2)} GB`;if(v>1024**2)return `${(v/1024**2).toFixed(1)} MB`;return `${v} B`}
onMounted(loadSources)
</script>
<template>
<div class="ds-page ds-page--wide metadata-page">
  <PageHeader title="元数据目录" subtitle="从真实数据源浏览数据库、表、字段与血缘，不复制数据资产信息。" />
  <div v-if="error" class="ds-error">{{error}}</div>
  <div class="catalog ds-card" v-loading="loading">
    <aside class="source-pane"><div class="pane-title">数据源 / 数据库</div><el-select v-model="sourceId" style="width:100%" @change="selectSource"><el-option v-for="s in sources" :key="s.id" :label="s.name" :value="s.id"/></el-select><div class="db-list"><button v-for="d in databases" :key="d.name" :class="{active:database===d.name}" @click="selectDatabase(d.name)"><span class="db-icon">DB</span><span>{{d.name}}</span></button></div></aside>
    <section class="table-pane"><div class="pane-title row"><span>表</span><span class="count">{{filteredTables.length}}</span></div><el-input v-model="keyword" placeholder="搜索表名 / 注释" clearable/><div class="table-list"><button v-for="t in filteredTables" :key="t.name" :class="{active:table?.name===t.name}" @click="selectTable(t)"><strong>{{t.name}}</strong><small>{{t.comment||t.type||'数据表'}}</small></button><div v-if="!filteredTables.length" class="ds-empty">暂无表</div></div></section>
    <section class="detail-pane"><template v-if="table"><div class="detail-head"><div><h2>{{database}}.{{table.name}}</h2><p>{{table.comment||'暂无表注释'}}</p></div><el-tag>{{table.type||'TABLE'}}</el-tag></div><div class="profile-grid"><div><label>负责人</label><strong>{{profile?.owner||'未设置'}}</strong></div><div><label>行数</label><strong>{{profile?.rowCount?.toLocaleString()||'—'}}</strong></div><div><label>估算大小</label><strong>{{fmtSize(profile?.estimatedSizeBytes)}}</strong></div><div><label>更新时间</label><strong>{{profile?.updateTime||'—'}}</strong></div></div><el-tabs><el-tab-pane label="字段"><el-table :data="columns" height="420"><el-table-column prop="name" label="字段" min-width="160"/><el-table-column prop="dataType" label="类型" width="150"/><el-table-column prop="nullable" label="可空" width="80"><template #default="s">{{s.row.nullable===false?'否':'是'}}</template></el-table-column><el-table-column prop="comment" label="说明" min-width="220" show-overflow-tooltip/></el-table></el-tab-pane><el-tab-pane label="血缘"><div v-if="lineage.length" class="lineage-list"><div v-for="l in lineage" :key="l.id"><span>{{l.sourceTable}}</span><b>→</b><span>{{l.targetTable}}</span><el-tag size="small" type="info">{{l.relationType}}</el-tag></div></div><div v-else class="ds-empty">暂无已解析血缘</div></el-tab-pane></el-tabs></template><div v-else class="ds-empty">选择左侧数据表查看详情</div></section>
  </div>
</div>
</template>
<style scoped>
.metadata-page{height:calc(100vh - var(--ds-topbar));display:flex;flex-direction:column}.catalog{min-height:0;flex:1;display:grid;grid-template-columns:230px 330px minmax(0,1fr);overflow:hidden}.source-pane,.table-pane{padding:16px;border-right:1px solid var(--ds-border);overflow:auto}.detail-pane{min-width:0;padding:18px;overflow:auto}.pane-title{font-weight:650;margin-bottom:12px}.pane-title.row{display:flex}.count{margin-left:auto;color:var(--ds-text-tertiary)}.db-list,.table-list{display:flex;flex-direction:column;gap:4px;margin-top:12px}.db-list button,.table-list button{border:0;background:transparent;border-radius:7px;text-align:left;padding:9px 10px;cursor:pointer;color:#475467}.db-list button.active,.table-list button.active{background:var(--ds-brand-soft);color:var(--ds-brand)}.db-icon{font-size:9px;margin-right:8px}.table-list strong,.table-list small{display:block}.table-list small{margin-top:3px;color:var(--ds-text-tertiary);font-size:11px}.detail-head{display:flex;justify-content:space-between;border-bottom:1px solid var(--ds-border-soft);padding-bottom:14px}.detail-head h2{font-size:18px;margin:0}.detail-head p{color:var(--ds-text-tertiary);margin:5px 0 0}.profile-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.profile-grid>div{border:1px solid var(--ds-border-soft);border-radius:7px;padding:11px}.profile-grid label,.profile-grid strong{display:block}.profile-grid label{font-size:11px;color:var(--ds-text-tertiary)}.profile-grid strong{margin-top:6px;font-size:12px}.lineage-list{display:flex;flex-direction:column;gap:8px}.lineage-list>div{display:grid;grid-template-columns:1fr 40px 1fr auto;align-items:center;padding:11px;border:1px solid var(--ds-border-soft);border-radius:7px}.lineage-list b{text-align:center;color:var(--ds-brand)}
</style>
