<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { dataSourceApi, type DataSourceView } from '../../api/platform'
import { integrationApi, type IntegrationTask, type IntegrationInstance } from '../../api/domain'

const tasks=ref<IntegrationTask[]>([]), sources=ref<DataSourceView[]>([]), latest=ref<Record<number,IntegrationInstance|undefined>>({}), loading=ref(false), dialog=ref(false), saving=ref(false)
const sourceDbs=ref<string[]>([]), sourceTables=ref<Array<{name:string;comment?:string}>>([])
const form=reactive({name:'',sourceDataSourceId:0,targetDataSourceId:0,sourceDatabase:'',targetDatabase:'ods',selectedTables:[] as string[],syncMode:'FULL',where:'',clusterId:''})
const mysql=computed(()=>sources.value.filter(s=>s.type==='MYSQL')), starrocks=computed(()=>sources.value.filter(s=>s.type==='STARROCKS'))
async function load(){loading.value=true;try{tasks.value=(await integrationApi.list()).filter(t=>t.syncMode!=='REALTIME');sources.value=await dataSourceApi.list();for(const t of tasks.value){const ins=await integrationApi.instances(t.id);latest.value[t.id]=ins[0]}}catch(e){ElMessage.error(msg(e))}finally{loading.value=false}}
function openCreate(){Object.assign(form,{name:'',sourceDataSourceId:mysql.value[0]?.id||0,targetDataSourceId:starrocks.value[0]?.id||0,sourceDatabase:'',targetDatabase:'ods',selectedTables:[],syncMode:'FULL',where:'',clusterId:''});dialog.value=true;if(form.sourceDataSourceId)void loadSourceDbs()}
async function loadSourceDbs(){if(!form.sourceDataSourceId)return;sourceDbs.value=(await integrationApi.sourceDatabases(form.sourceDataSourceId)).map(x=>x.name);if(!sourceDbs.value.includes(form.sourceDatabase))form.sourceDatabase=sourceDbs.value[0]||'';await loadSourceTables()}
async function loadSourceTables(){if(!form.sourceDataSourceId||!form.sourceDatabase)return;sourceTables.value=await integrationApi.sourceTables(form.sourceDataSourceId,form.sourceDatabase);form.selectedTables=[]}
async function create(){if(!form.name||!form.sourceDataSourceId||!form.targetDataSourceId||!form.sourceDatabase||!form.targetDatabase||!form.selectedTables.length)return ElMessage.warning('请完整选择来源、目标和同步表');if(form.syncMode==='INCREMENTAL'&&!form.where)return ElMessage.warning('增量同步需要 WHERE 条件');const source=sources.value.find(s=>s.id===form.sourceDataSourceId)!,target=sources.value.find(s=>s.id===form.targetDataSourceId)!;saving.value=true;try{await integrationApi.create({name:form.name,sourceType:'MYSQL',targetType:'STARROCKS',syncMode:form.syncMode,sourceDataSourceId:source.id,targetDataSourceId:target.id,source:{host:source.host,port:source.port,database:form.sourceDatabase,username:source.username,password:'',table:form.selectedTables[0]},target:{host:target.host,port:target.port,database:form.targetDatabase,username:target.username,password:'',table:`ods_${form.selectedTables[0]}`},mappings:[],options:{where:form.where,clusterId:form.clusterId||undefined,schemaSaveMode:'CREATE_SCHEMA_WHEN_NOT_EXIST'},tables:form.selectedTables.map(t=>({sourceDatabase:form.sourceDatabase,sourceTable:t,targetDatabase:form.targetDatabase,targetTable:`ods_${t}`}))});dialog.value=false;ElMessage.success('离线同步任务已创建');await load()}catch(e){ElMessage.error(msg(e))}finally{saving.value=false}}
async function run(t:IntegrationTask){try{await integrationApi.validate(t.id);await integrationApi.run(t.id);ElMessage.success('SeaTunnel 任务已提交');setTimeout(load,800)}catch(e){ElMessage.error(msg(e))}}
async function stop(t:IntegrationTask){try{await integrationApi.stop(t.id);ElMessage.success('停止请求已提交');await load()}catch(e){ElMessage.error(msg(e))}}
async function remove(t:IntegrationTask){try{await ElMessageBox.confirm(`删除“${t.name}”？`,'删除任务',{type:'warning'});await integrationApi.remove(t.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(msg(e))}}
function path(t:IntegrationTask){const s=t.tables?.[0];return s?`${s.sourceDatabase} → ${s.targetDatabase}`:`${t.sourceType} → ${t.targetType}`}
function msg(e:unknown){return e instanceof Error?e.message:'操作失败'}
watch(()=>form.sourceDataSourceId,loadSourceDbs);watch(()=>form.sourceDatabase,loadSourceTables);onMounted(load)
</script>
<template><div class="ds-page"><PageHeader title="离线同步" subtitle="SeaTunnel 负责 MySQL → StarRocks 批量同步；调度统一由工作流引用任务。"><template #actions><el-button type="primary" @click="openCreate">+ 新建离线同步</el-button></template></PageHeader><div class="ds-card"><div class="ds-toolbar"><strong>同步任务</strong><div class="ds-spacer"/><el-button @click="load" :loading="loading">刷新</el-button></div><el-table :data="tasks" v-loading="loading"><el-table-column prop="name" label="任务名称" min-width="180"/><el-table-column label="来源 → 目标" min-width="190"><template #default="s">{{path(s.row)}}</template></el-table-column><el-table-column label="表数" width="80"><template #default="s">{{s.row.tables?.length||0}}</template></el-table-column><el-table-column prop="syncMode" label="方式" width="110"/><el-table-column label="最近状态" width="130"><template #default="s"><StatusBadge :status="latest[s.row.id]?.status||'未运行'"/></template></el-table-column><el-table-column label="最近运行" min-width="160"><template #default="s">{{latest[s.row.id]?.startedAt||'—'}}</template></el-table-column><el-table-column label="操作" width="220"><template #default="s"><el-button link type="primary" @click="run(s.row)">运行</el-button><el-button link @click="stop(s.row)">停止</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table></div>
<el-dialog v-model="dialog" title="新建离线同步" width="720px"><el-form label-position="top"><div class="grid"><el-form-item label="任务名称"><el-input v-model="form.name" placeholder="例如 ods_order_full"/></el-form-item><el-form-item label="同步方式"><el-select v-model="form.syncMode"><el-option label="全量同步" value="FULL"/><el-option label="条件增量" value="INCREMENTAL"/></el-select></el-form-item><el-form-item label="MySQL 来源"><el-select v-model="form.sourceDataSourceId"><el-option v-for="s in mysql" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="源数据库"><el-select v-model="form.sourceDatabase"><el-option v-for="d in sourceDbs" :key="d" :label="d" :value="d"/></el-select></el-form-item><el-form-item label="StarRocks 目标"><el-select v-model="form.targetDataSourceId"><el-option v-for="s in starrocks" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="目标数据库"><el-input v-model="form.targetDatabase"/></el-form-item></div><el-form-item label="同步表"><el-select v-model="form.selectedTables" multiple filterable collapse-tags style="width:100%"><el-option v-for="t in sourceTables" :key="t.name" :label="t.comment?`${t.name} · ${t.comment}`:t.name" :value="t.name"/></el-select></el-form-item><el-form-item v-if="form.syncMode==='INCREMENTAL'" label="WHERE 条件"><el-input v-model="form.where" placeholder="例如 updated_at >= DATE_SUB(NOW(), INTERVAL 1 DAY)"/></el-form-item><el-form-item label="SeaTunnel 集群 ID（可选）"><el-input v-model="form.clusterId" placeholder="留空使用默认执行环境"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建任务</el-button></template></el-dialog></div></template>
<style scoped>.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}</style>
