<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { dataSourceApi, type DataSourceView } from '../../api/platform'
import { flinkApi, realtimeApi, releaseApi, type FlinkEnvironment, type RealtimeJob } from '../../api/domain'

const loading=ref(true), saving=ref(false), editorVisible=ref(false), yamlLoading=ref(false)
const rows=ref<RealtimeJob[]>([]), sources=ref<DataSourceView[]>([]), envs=ref<FlinkEnvironment[]>([])
const current=ref<RealtimeJob|null>(null), editorMode=ref<'GUIDE'|'YAML'>('GUIDE'), yamlText=ref('')
const form=reactive<any>({name:'',description:'',runtimeEnvironmentId:undefined,sourceDataSourceId:undefined,sinkDataSourceId:undefined,sourceDatabase:'',sinkDatabase:'ods',sourceTable:'',targetTable:'',startupMode:'initial',timezone:'Asia/Shanghai',serverId:'5400-5499',chunkSize:8096,fetchSize:1024,heartbeatMs:30000,parallelism:1,schemaEvolution:'EVOLVE',maxBytes:67108864,flushIntervalMs:2000,transactionStreamLoad:true})
const mysqlSources=computed(()=>sources.value.filter(x=>x.type==='MYSQL')), starrocksSources=computed(()=>sources.value.filter(x=>x.type==='STARROCKS'))
function spec(){return editorMode.value==='YAML'?{editorMode:'YAML',yaml:yamlText.value}:{editorMode:'GUIDE',name:form.name,sourceDataSourceId:form.sourceDataSourceId,sinkDataSourceId:form.sinkDataSourceId,sourceDatabase:form.sourceDatabase,sinkDatabase:form.sinkDatabase,tables:form.sourceTable?[{sourceTable:form.sourceTable,targetTable:form.targetTable||form.sourceTable}]:[],startupMode:form.startupMode,timezone:form.timezone,serverId:form.serverId,chunkSize:form.chunkSize,fetchSize:form.fetchSize,heartbeatMs:form.heartbeatMs,parallelism:form.parallelism,schemaEvolution:form.schemaEvolution,sink:{maxBytes:form.maxBytes,flushIntervalMs:form.flushIntervalMs,transactionStreamLoad:form.transactionStreamLoad}}}
function reset(){current.value=null;editorMode.value='GUIDE';yamlText.value='';Object.assign(form,{name:'',description:'',runtimeEnvironmentId:envs.value.find(x=>x.defaultEnvironment)?.id,sourceDataSourceId:mysqlSources.value[0]?.id,sinkDataSourceId:starrocksSources.value[0]?.id,sourceDatabase:mysqlSources.value[0]?.databaseName||'',sinkDatabase:starrocksSources.value[0]?.databaseName||'ods',sourceTable:'',targetTable:'',startupMode:'initial',timezone:'Asia/Shanghai',serverId:'5400-5499',chunkSize:8096,fetchSize:1024,heartbeatMs:30000,parallelism:1,schemaEvolution:'EVOLVE',maxBytes:67108864,flushIntervalMs:2000,transactionStreamLoad:true})}
async function load(){loading.value=true;try{[rows.value,sources.value,envs.value]=await Promise.all([realtimeApi.list(),dataSourceApi.list(),flinkApi.list()])}catch(e){ElMessage.error(e instanceof Error?e.message:'实时任务加载失败')}finally{loading.value=false}}
function openCreate(){reset();editorVisible.value=true}
async function openEdit(row:RealtimeJob){current.value=await realtimeApi.get(row.id);const s:any=current.value.spec||{};editorMode.value=s.editorMode==='YAML'?'YAML':'GUIDE';yamlText.value=String(s.yaml||'');Object.assign(form,{name:current.value.name,description:current.value.description||'',runtimeEnvironmentId:current.value.runtimeEnvironmentId,sourceDataSourceId:s.sourceDataSourceId,sinkDataSourceId:s.sinkDataSourceId,sourceDatabase:s.sourceDatabase||'',sinkDatabase:s.sinkDatabase||'ods',sourceTable:s.tables?.[0]?.sourceTable||'',targetTable:s.tables?.[0]?.targetTable||'',startupMode:s.startupMode||'initial',timezone:s.timezone||'Asia/Shanghai',serverId:s.serverId||'5400-5499',chunkSize:s.chunkSize||8096,fetchSize:s.fetchSize||1024,heartbeatMs:s.heartbeatMs||30000,parallelism:s.parallelism||1,schemaEvolution:s.schemaEvolution||'EVOLVE',maxBytes:s.sink?.maxBytes||67108864,flushIntervalMs:s.sink?.flushIntervalMs||2000,transactionStreamLoad:s.sink?.transactionStreamLoad!==false});editorVisible.value=true}
async function save(){if(!form.name.trim())return ElMessage.warning('请输入任务名称');saving.value=true;try{const payload={name:form.name,description:form.description,runtimeEnvironmentId:form.runtimeEnvironmentId,spec:spec()};current.value=current.value?await realtimeApi.draft(current.value.id,payload):await realtimeApi.create(payload);ElMessage.success('草稿已保存');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{saving.value=false}}
async function validateJob(){if(!current.value)await save();if(!current.value)return;try{const v=await realtimeApi.validate(current.value.id);yamlText.value=v.yamlPreview||yamlText.value;ElMessage.success(v.message||'配置校验通过')}catch(e){ElMessage.error(e instanceof Error?e.message:'校验失败')}}
async function publish(){if(!current.value){await save();if(!current.value)return}try{await releaseApi.request({resourceType:'REALTIME',resourceId:current.value.id,resourceName:form.name,requestedVersion:current.value.definitionVersion});ElMessage.success('发布请求已处理');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'发布失败')}}
async function start(row:RealtimeJob){try{await realtimeApi.start(row.id);ElMessage.success('启动请求已提交');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'启动失败')}}
async function stop(row:RealtimeJob){try{await ElMessageBox.confirm(`停止“${row.name}”？`,'停止实时任务',{type:'warning'});await realtimeApi.stop(row.id);ElMessage.success('已停止');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'停止失败')}}
async function switchMode(mode:'GUIDE'|'YAML'){if(mode===editorMode.value)return;if(mode==='YAML'&&current.value){yamlLoading.value=true;try{yamlText.value=await realtimeApi.yaml(current.value.id)}catch{}finally{yamlLoading.value=false}}editorMode.value=mode}
function releaseLabel(row:RealtimeJob){return row.publishedUpdateAvailable?'有未发布修改':row.releaseState}
onMounted(load)
</script>
<template><div class="ds-page">
<PageHeader title="实时同步" subtitle="使用独立 Flink CDC 管理 MySQL Binlog 到 StarRocks 的实时同步。"><template #actions><el-button type="primary" @click="openCreate">+ 新建实时同步</el-button></template></PageHeader>
<div class="ds-card"><div class="ds-toolbar"><strong>实时任务</strong><div class="ds-spacer"/><el-button @click="load" :loading="loading">刷新</el-button></div><el-skeleton v-if="loading" :rows="6" animated/><div v-else-if="!rows.length" class="ds-empty"><div><div class="ds-empty__title">暂无实时任务</div><div>创建后在单页编辑器中完成 Source、Sink、运行参数和发布。</div></div></div><table v-else class="ds-table"><thead><tr><th>名称</th><th>发布状态</th><th>运行状态</th><th>Desired</th><th>版本</th><th>Flink 环境</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><span class="ds-resource">{{r.name}}</span><div class="sub">{{r.description}}</div></td><td>{{releaseLabel(r)}}</td><td><StatusBadge :status="r.observedState"/></td><td>{{r.desiredState}}</td><td>草稿 V{{r.definitionVersion}} / 生产 V{{r.publishedVersion||'-'}}</td><td>{{envs.find(e=>e.id===r.runtimeEnvironmentId)?.name||'未配置'}}</td><td><span class="ds-link" @click="openEdit(r)">编辑</span><span class="sep">·</span><span v-if="r.observedState==='RUNNING'" class="danger" @click="stop(r)">停止</span><span v-else class="ds-link" @click="start(r)">启动</span></td></tr></tbody></table></div>
<el-drawer v-model="editorVisible" size="92%" direction="rtl" :with-header="false"><div class="editor-shell"><header><div><h2>{{current?'编辑实时同步':'新建实时同步'}}</h2><p>Definition / Runtime 分离；发布不会自动启动运行实例。</p></div><div class="actions"><el-button @click="validateJob">校验</el-button><el-button :loading="saving" @click="save">保存草稿</el-button><el-button type="primary" @click="publish">发布</el-button><el-button @click="editorVisible=false">关闭</el-button></div></header><div class="mode"><el-segmented :model-value="editorMode" :options="[{label:'向导模式',value:'GUIDE'},{label:'YAML 模式',value:'YAML'}]" @change="(v:any)=>switchMode(v)"/></div>
<div v-if="editorMode==='GUIDE'" class="editor-grid"><section class="ds-card config"><h3>任务与数据源</h3><el-form label-position="top"><div class="two"><el-form-item label="任务名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="Flink 环境"><el-select v-model="form.runtimeEnvironmentId" style="width:100%"><el-option v-for="e in envs" :key="e.id" :label="`${e.name} · Flink ${e.flinkVersion||'-'}`" :value="e.id"/></el-select></el-form-item><el-form-item label="MySQL Source"><el-select v-model="form.sourceDataSourceId" style="width:100%"><el-option v-for="s in mysqlSources" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="StarRocks Sink"><el-select v-model="form.sinkDataSourceId" style="width:100%"><el-option v-for="s in starrocksSources" :key="s.id" :label="s.name" :value="s.id"/></el-select></el-form-item><el-form-item label="源库"><el-input v-model="form.sourceDatabase"/></el-form-item><el-form-item label="目标库"><el-input v-model="form.sinkDatabase"/></el-form-item><el-form-item label="源表"><el-input v-model="form.sourceTable"/></el-form-item><el-form-item label="目标表"><el-input v-model="form.targetTable" placeholder="默认与源表同名"/></el-form-item></div><el-form-item label="描述"><el-input v-model="form.description"/></el-form-item></el-form></section>
<section class="ds-card config"><h3>启动与运行参数</h3><el-form label-position="top"><div class="two"><el-form-item label="启动方式"><el-select v-model="form.startupMode" style="width:100%"><el-option label="初始化 + 持续增量" value="initial"/><el-option label="仅从最新位点" value="latest-offset"/><el-option label="指定时间" value="timestamp"/><el-option label="指定 Binlog / GTID" value="specific-offset"/></el-select></el-form-item><el-form-item label="时区"><el-input v-model="form.timezone"/></el-form-item><el-form-item label="Server ID"><el-input v-model="form.serverId"/></el-form-item><el-form-item label="并行度"><el-input-number v-model="form.parallelism" :min="1" :max="128" style="width:100%"/></el-form-item><el-form-item label="Chunk Size"><el-input-number v-model="form.chunkSize" :min="1" style="width:100%"/></el-form-item><el-form-item label="Fetch Size"><el-input-number v-model="form.fetchSize" :min="1" style="width:100%"/></el-form-item><el-form-item label="Heartbeat(ms)"><el-input-number v-model="form.heartbeatMs" :min="1000" style="width:100%"/></el-form-item><el-form-item label="Schema 变化"><el-select v-model="form.schemaEvolution" style="width:100%"><el-option label="自动演进" value="EVOLVE"/><el-option label="忽略" value="IGNORE"/><el-option label="失败" value="EXCEPTION"/></el-select></el-form-item><el-form-item label="Sink Buffer(Bytes)"><el-input-number v-model="form.maxBytes" :min="67108864" style="width:100%"/></el-form-item><el-form-item label="Flush Interval(ms)"><el-input-number v-model="form.flushIntervalMs" :min="100" style="width:100%"/></el-form-item><el-form-item label="Transaction Stream Load"><el-switch v-model="form.transactionStreamLoad"/></el-form-item></div></el-form></section></div>
<div v-else class="yaml-wrap"><div class="yaml-note">YAML 模式直接保存并提交 Flink CDC Pipeline YAML；密码不会从平台数据源配置回显。</div><el-input v-model="yamlText" type="textarea" :rows="28" :loading="yamlLoading" class="yaml-editor" spellcheck="false"/></div></div></el-drawer>
</div></template>
<style scoped>.sub{font-size:11px;color:var(--ds-text-tertiary);margin-top:3px}.sep{margin:0 7px;color:#d0d5dd}.danger{color:#d92d20;cursor:pointer}.editor-shell{min-height:100%;background:#f7f8fa}.editor-shell>header{height:72px;display:flex;align-items:center;padding:0 22px;background:#fff;border-bottom:1px solid var(--ds-border)}h2{margin:0;font-size:18px}header p{margin:4px 0 0;color:#98a2b3;font-size:11px}.actions{margin-left:auto;display:flex;gap:8px}.mode{padding:14px 20px 0}.editor-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:14px 20px 24px}.config{padding:18px}.config h3{margin:0 0 16px;font-size:14px}.two{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.yaml-wrap{padding:14px 20px}.yaml-note{margin-bottom:10px;padding:10px 12px;border:1px solid #d0d5dd;border-radius:7px;background:#fff;color:#667085;font-size:12px}.yaml-editor :deep(textarea){font-family:Consolas,monospace;font-size:12px;line-height:1.6}</style>