<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { Graph } from '@antv/x6'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import { developmentApi, releaseApi, workflowApi, type DevFile, type FileVersion, type WorkflowNode, type WorkflowView } from '../../api/domain'

const loading=ref(true), rows=ref<WorkflowView[]>([]), drawer=ref(false), saving=ref(false)
const current=ref<WorkflowView|null>(null), selectedCode=ref(''), files=ref<DevFile[]>([]), versions=ref<FileVersion[]>([])
const form=reactive({name:'',description:''}); const nodeDraft=reactive<any>({name:'',nodeType:'SQL',fileVersionId:undefined,configJson:'{}'})
let graph:Graph|undefined
async function load(){loading.value=true;try{rows.value=await workflowApi.list()}catch(e){ElMessage.error(e instanceof Error?e.message:'工作流加载失败')}finally{loading.value=false}}
async function loadFiles(){try{const ps=await developmentApi.projects();if(!ps.length)return;files.value=(await Promise.all(ps.map(p=>developmentApi.files(p.id)))).flat()}catch{}}
async function loadVersions(fileId:number){versions.value=await developmentApi.versions(fileId)}
function newWorkflow(){current.value=null;form.name='';form.description='';drawer.value=true;selectedCode.value='';nextTick(initGraph)}
async function edit(row:WorkflowView){current.value=await workflowApi.get(row.id);form.name=current.value.name;form.description=current.value.description||'';drawer.value=true;selectedCode.value='';await nextTick();initGraph(current.value)}
function initGraph(w?:WorkflowView|null){graph?.dispose();graph=new Graph({container:document.getElementById('workflowCanvas')!,background:{color:'#fbfcfe'},grid:{visible:true,size:16,type:'dot',args:{color:'#e5e7eb'}},panning:true,mousewheel:{enabled:true,modifiers:['ctrl','meta'],minScale:.5,maxScale:1.5},connecting:{router:'orth',connector:'rounded',anchor:'center',connectionPoint:'boundary',allowBlank:false,snap:true}});if(w){const idToCode=new Map(w.nodes.map(n=>[n.id,n.nodeCode]));w.nodes.forEach(n=>addGraphNode(n));w.edges.forEach(e=>{const s=idToCode.get(e.sourceNodeId),t=idToCode.get(e.targetNodeId);if(s&&t)graph?.addEdge({source:s,target:t,attrs:{line:{stroke:'#98a2b3',targetMarker:'classic'}}})})}graph.on('node:click',({node})=>selectNode(String(node.id)))}
function addGraphNode(n?:Partial<WorkflowNode>){if(!graph)return;const code=n?.nodeCode||`node_${Date.now()}_${Math.random().toString(16).slice(2,6)}`;graph.addNode({id:code,x:n?.x??80+graph.getNodes().length*190,y:n?.y??130,width:154,height:60,label:n?.name||'新节点',data:{name:n?.name||'新节点',nodeType:n?.nodeType||'SQL',fileVersionId:n?.fileVersionId,configJson:n?.configJson||'{}'},attrs:{body:{fill:'#fff',stroke:'#b7c4ff',rx:8,ry:8},label:{fill:'#344054',fontSize:12,fontWeight:600}},ports:{groups:{in:{position:'left',attrs:{circle:{r:4,magnet:true,stroke:'#8291d8',fill:'#fff'}}},out:{position:'right',attrs:{circle:{r:4,magnet:true,stroke:'#8291d8',fill:'#fff'}}}},items:[{id:'in',group:'in'},{id:'out',group:'out'}]}});selectNode(code)}
function addKind(type:'SQL'|'SEATUNNEL'|'CONDITION'){addGraphNode({name:type==='SQL'?'StarRocks SQL':type==='SEATUNNEL'?'SeaTunnel 离线同步':'条件分支',nodeType:type})}
function selectNode(code:string){selectedCode.value=code;const n=graph?.getCellById(code);if(!n||!n.isNode())return;const d:any=n.getData();Object.assign(nodeDraft,{name:d.name||'',nodeType:d.nodeType||'SQL',fileVersionId:d.fileVersionId,configJson:d.configJson||'{}'})}
function applyNode(){const n=graph?.getCellById(selectedCode.value);if(!n||!n.isNode())return;n.setData({...nodeDraft});n.setAttrs({label:{text:nodeDraft.name}});ElMessage.success('节点配置已更新')}
function removeNode(){const n=graph?.getCellById(selectedCode.value);if(n){graph?.removeCell(n);selectedCode.value=''}}
async function chooseFile(fileId:number){await loadVersions(fileId);nodeDraft.fileVersionId=versions.value[0]?.id}
function payload(){const nodes=(graph?.getNodes()||[]).map(n=>{const p=n.getPosition(),d:any=n.getData();return{name:d.name,nodeType:d.nodeType,fileVersionId:d.fileVersionId||undefined,configJson:d.configJson||'{}',x:Math.round(p.x),y:Math.round(p.y),nodeCode:String(n.id)}});const edges=(graph?.getEdges()||[]).map(e=>({sourceNodeCode:String(e.getSourceCellId()),targetNodeCode:String(e.getTargetCellId())}));return{name:form.name,description:form.description,nodes,edges}}
async function save(){if(!form.name.trim())return ElMessage.warning('请输入工作流名称');saving.value=true;try{current.value=current.value?await workflowApi.update(current.value.id,payload() as any):await workflowApi.create(payload() as any);ElMessage.success('工作流草稿已保存');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{saving.value=false}}
async function publish(){if(!current.value){await save();if(!current.value)return}try{await releaseApi.request({resourceType:'WORKFLOW',resourceId:current.value.id,resourceName:form.name,requestedVersion:current.value.publishedVersion+1});ElMessage.success('发布请求已处理');await load()}catch(e){ElMessage.error(e instanceof Error?e.message:'发布失败')}}
async function run(r:WorkflowView){try{await workflowApi.run(r.id);ElMessage.success('运行实例已提交')}catch(e){ElMessage.error(e instanceof Error?e.message:'运行失败')}}
async function remove(r:WorkflowView){try{await ElMessageBox.confirm(`删除“${r.name}”？`,'删除工作流',{type:'warning'});await workflowApi.remove(r.id);await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e instanceof Error?e.message:'删除失败')}}
onMounted(()=>{load();loadFiles()});onBeforeUnmount(()=>graph?.dispose())
</script>
<template><div class="ds-page"><PageHeader title="工作流定义" subtitle="使用平台 Scheduler 编排 StarRocks SQL、SeaTunnel 离线同步与条件依赖。"><template #actions><el-button type="primary" @click="newWorkflow">+ 新建工作流</el-button></template></PageHeader><div class="ds-card"><div class="ds-toolbar"><strong>工作流</strong><div class="ds-spacer"/><el-button @click="load">刷新</el-button></div><el-skeleton v-if="loading" :rows="6" animated/><div v-else-if="!rows.length" class="ds-empty"><div><div class="ds-empty__title">暂无工作流</div><div>先创建工作流，再在 DAG 画布配置任务依赖。</div></div></div><table v-else class="ds-table"><thead><tr><th>名称</th><th>编码</th><th>状态</th><th>生产版本</th><th>节点数</th><th>操作</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td class="ds-resource">{{r.name}}</td><td>{{r.workflowCode}}</td><td><StatusBadge :status="r.status"/></td><td>V{{r.publishedVersion||'-'}}</td><td>{{r.nodes.length}}</td><td><span class="ds-link" @click="edit(r)">编辑</span><span class="sep">·</span><span class="ds-link" @click="run(r)">运行</span><span class="sep">·</span><span class="danger" @click="remove(r)">删除</span></td></tr></tbody></table></div>
<el-drawer v-model="drawer" size="96%" :with-header="false"><div class="dag-shell"><header><div><h2>{{current?'编辑工作流':'新建工作流'}}</h2><p>草稿编辑与生产版本分离；Flink CDC 不作为 DAG 节点。</p></div><div class="actions"><el-button :loading="saving" @click="save">保存草稿</el-button><el-button type="primary" @click="publish">发布</el-button><el-button @click="drawer=false">关闭</el-button></div></header><div class="basic"><el-input v-model="form.name" placeholder="工作流名称"/><el-input v-model="form.description" placeholder="描述"/></div><div class="dag-grid"><aside class="library"><h3>节点库</h3><button @click="addKind('SQL')">▤ StarRocks SQL</button><button @click="addKind('SEATUNNEL')">⇄ SeaTunnel 离线同步</button><button @click="addKind('CONDITION')">◇ 条件分支</button><div class="hint">从节点右侧连接点拖到下游节点左侧连接点建立依赖。</div></aside><main id="workflowCanvas" class="canvas"></main><aside class="config"><h3>节点设置</h3><div v-if="!selectedCode" class="empty-config">选择画布节点后编辑配置。</div><el-form v-else label-position="top"><el-form-item label="节点名称"><el-input v-model="nodeDraft.name"/></el-form-item><el-form-item label="类型"><el-select v-model="nodeDraft.nodeType" style="width:100%"><el-option label="StarRocks SQL" value="SQL"/><el-option label="SeaTunnel" value="SEATUNNEL"/><el-option label="条件分支" value="CONDITION"/></el-select></el-form-item><template v-if="nodeDraft.nodeType==='SQL'"><el-form-item label="开发文件"><el-select style="width:100%" placeholder="选择 SQL 文件" @change="chooseFile"><el-option v-for="f in files.filter(x=>x.fileType==='SQL')" :key="f.id" :label="f.name" :value="f.id"/></el-select></el-form-item><el-form-item label="文件版本"><el-select v-model="nodeDraft.fileVersionId" style="width:100%"><el-option v-for="v in versions" :key="v.id" :label="`V${v.versionNo}`" :value="v.id"/></el-select></el-form-item></template><el-form-item label="节点配置(JSON)"><el-input v-model="nodeDraft.configJson" type="textarea" :rows="7"/></el-form-item><el-button type="primary" @click="applyNode">应用配置</el-button><el-button type="danger" plain @click="removeNode">删除节点</el-button></el-form></aside></div></div></el-drawer></div></template>
<style scoped>.sep{margin:0 7px;color:#d0d5dd}.danger{color:#d92d20;cursor:pointer}.dag-shell{height:100vh;display:flex;flex-direction:column;background:#f7f8fa}.dag-shell>header{height:68px;display:flex;align-items:center;padding:0 18px;border-bottom:1px solid var(--ds-border);background:#fff}.dag-shell h2{margin:0;font-size:18px}.dag-shell header p{margin:3px 0 0;color:#98a2b3;font-size:11px}.actions{margin-left:auto;display:flex;gap:8px}.basic{height:56px;display:grid;grid-template-columns:260px 1fr;gap:10px;padding:10px 14px;background:#fff;border-bottom:1px solid var(--ds-border)}.dag-grid{flex:1;min-height:0;display:grid;grid-template-columns:210px minmax(0,1fr) 280px}.library,.config{background:#fff;padding:14px;border-right:1px solid var(--ds-border);overflow:auto}.config{border-right:0;border-left:1px solid var(--ds-border)}.library h3,.config h3{margin:0 0 14px;font-size:14px}.library button{width:100%;height:42px;margin-bottom:8px;text-align:left;padding:0 10px;border:1px solid var(--ds-border);border-radius:7px;background:#fff;cursor:pointer}.library button:hover{border-color:#aeb8ff;background:#fafbff}.hint,.empty-config{font-size:11px;line-height:1.6;color:#98a2b3;margin-top:12px}.canvas{min-width:0;overflow:hidden;background:#fbfcfe}</style>